### ISSUE TITLE
Can't load 20gb dataset.

### ISSUE THREAD

**Issue by heyapps** [ultralytics/hub#123]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Can't load 20gb custom dataset. Unknown error on scanning step.

**Comment by kalenmike** [comment]
@heyapps Sorry to hear that you are having issues with your dataset. With the information you have given it is difficult for me to help to identify the issue. May I suggest that you amend your dataset to make it smaller and try the upload again. You can do this by copying the dataset structure but using only 6 images and the associated labels. Smaller datasets will check for the most common errors before upload.

**Comment by heyapps** [comment]
@kalenmike i did it with a small dataset and it works perfect, maybe its ultalytics processing error while scanning phase of the 20gb custom dataset?

**Comment by kalenmike** [comment]
@heyapps Ok thanks, yes it seems likely. Are you able to share your dataset with me so that I can do some troubleshooting? If its private and you prefer not to share it could you just provide me with some stats so I can look into the issue, for example 
- the count of images and labels
- how many splits
- the average image size in MB
