### ISSUE TITLE
I am getting processing error while uploading dataset.

### ISSUE THREAD

**Issue by richedperson1** [ultralytics/hub#135]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

 I follow same step as it mention in document. Create YAML file as same name as directory but still getting processing error while loading dataset. I try to change name of images valid folder name as val but still error remain constant.

YAML file : 
![yaml file](https://user-images.githubusercontent.com/62417643/210507120-6a3c5e57-d27f-45da-9c78-0a69f824066a.PNG)

Directory : 
![directory error](https://user-images.githubusercontent.com/62417643/210507133-66e44af7-ea44-48ee-8890-991d949e47b2.PNG)

Images directory: 
![imagesDirectory](https://user-images.githubusercontent.com/62417643/210508427-5fb1d682-8139-4272-a366-d9f516556d7c.PNG)

**Comment by kalenmike** [comment]
@richedperson1 Thanks for reaching out. Have you had a chance to look at our example dataset? This may help you figure out what is wrong with the formatting:

https://github.com/ultralytics/hub#1-upload-a-dataset

If you can't find the issue I could take a look but you would need to send me the dataset.

**Comment by richedperson1** [comment]
I already look into the dataset required format [guidalines shown on this https://github.com/ultralytics/hub#1-upload-a-dataset ] but Not find the solution. It getting error when scanning happen.

My dataset is : https://drive.google.com/file/d/1mD5Y4Ykhqy5GFggGB1k-Gp0wuao2sRJR/view?usp=sharing

**Comment by kalenmike** [comment]
@richedperson1 Thanks for sending through the dataset. I can confirm there is an issue during scanning. 

Your dataset is formatted correctly as shown in this small example dataset which uses the first 3 images from each split:
[helmet-small.zip](https://github.com/ultralytics/hub/files/10344133/helmet-small.zip)

I cannot say for certain what the problem is but it looks like it could have an issue somewhere in the labels:

` VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([
Unhandled Error :  operands could not be broadcast together with shapes (2,) (3,) `

As the dataset has 55555 images its difficult for me to track down the exact issue.

Are you able to use this dataset in other places?

**Comment by kalenmike** [comment]
@richedperson1 If I remove your validation labels then the dataset processes fine. So I would start there.

**Comment by richedperson1** [comment]
Thank you, When I remove validation dataset it will not raising error. I got confusion why validarion not working ?

**Comment by kalenmike** [comment]
@richedperson1 My guess would be that there is something wrong with one of your validation labels. Perhaps a formatting error?

**Comment by UltralyticsAssistant** [comment]
@richedperson1 you're welcome! If you run into any further issues or have additional questions, feel free to reach out. Good luck with your project!
