### ISSUE TITLE
Datasets Labelling

### ISSUE THREAD

**Issue by Forfy-code** [ultralytics/hub#148]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I'll be talking about Ultralytics' new hub.

Do the images of the dataset need to be labelled?
What format must these images have?
Where can I tag my images?

Thank you very much.

**Comment by kalenmike** [comment]
@Forfy-code Thank you for the questions.

1. In order to train a dataset in Ultralytics HUB you will need a labeled dataset. We currently do not provide labeling tools however we have integrated with [Roboflow](https://roboflow.com/) who provide a data labeling tool.
2. We handle all standard image formats. You can see an [example dataset here](https://github.com/ultralytics/hub/blob/master/coco6.zip) as well as more detailed instructions for [creating a dataset here](https://github.com/ultralytics/hub#1-upload-a-dataset)
3. Your image labels should be set in the YAML file contained within your dataset.
