### ISSUE TITLE
The hub does not work for Russian users.

### ISSUE THREAD

**Issue by Pro100rus32** [ultralytics/hub#20]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin, Datasets

### Bug

It is impossible to download dataset and also to log in or register to the account from the Russian IP address.

### Environment

- Windows 11
- Chrome 100.0.4896.127

### Minimal Reproducible Example

1. Login to hub #use russian ip

**Comment by glenn-jocher** [comment]
@Pro100rus32 thanks for the bug report! 

One of our core values is universal access to AI for all. We think everyone should have the same opportunities no matter who they are or where they live. Indeed @alexeyab in Moscow has been an instrumental contributor to YOLO with https://github.com/AlexeyAB/darknet, and I think AI research and collaboration should rise above politics.

In the past we resolved similar issues with access in China, so I'll see what I can do to figure out what's going on try to find workarounds in possible.

**Comment by kalenmike** [comment]
@Pro100rus32 Thanks for bringing this to our attention. We have taken no action ourselves to block Russian IP addresses, however due to the recent sanctions several platforms have begun doing so. To help track down this issue further could you please answer the following questions:

1. With which accounts are you unable to register/login (Email, Google, GitHub, Apple)?
2. When you did gain access did you use a VPN/Proxy to change your IP?

Thanks for helping us to replicate and resolve this issue.

**Comment by Pro100rus32** [comment]
I apologize for the late response. **Everything works!**

_Thanks : )_

**Comment by glenn-jocher** [comment]
@Pro100rus32 yay! Thanks for the update.
