### ISSUE TITLE
Use examples don't seem to work

### ISSUE THREAD

**Issue by 173970984** [ultralytics/hub#22]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/7731320/164954931-2e53e9d7-5074-4d28-91ea-5172f9f9c76b.png)
Use examples don't seem to work

**Comment by glenn-jocher** [comment]
@173970984 thanks for the bug report! You are right this is a typo we have in our command! We'll have our web team fix this @kalenmike 

With your command it looks like your ultralytics or yolov5 code may simply be out of date. Can you try to update ultralytics and delete your local yolov5 copy and see if this fixes the problem:
```
pip install -U ultralytics
```

**Comment by kalenmike** [comment]
@173970984 @glenn-jocher The typo has been fixed for v0.1.14-beta.

**Comment by kalenmike** [comment]
@173970984 The error you are seeing in your screenshot:

`File "/home/ace/Developer/Websites/development/test-yolo/utils/general.py", line 186, in print_args
    LOGGER.info(colorstr(s) + ', '.join(f'{k}={v}' for k, v in args.items()))
AttributeError: 'str' object has no attribute 'items'
`
This is due to the way you have structured you folders. The Ultralytics pip package will clone YOLOv5 into ./yolov5 and it already bundles the file 'utils/general.py'. As you are running the Ultralytics package from inside an existing YOLOv5 directory you are forcing the Ultralytics pip package to use your version of 'utils/general.py' which happens to be a newer version with breaking changes than what the Ultralytics pip package has bundled.

We will make some changes on our end to prevent similar issues in the future. For now you only need to run the Ultralytics pip package in it own directory, and let the agent clone the supported version of YOLOv5. Eg:

/hub
--agent.py

**Comment by glenn-jocher** [comment]
@kalenmike maybe we should rename the utils directory in ultralytics?

**Comment by kalenmike** [comment]
@glenn-jocher That would be a quick way to solve this issue. Rename the utils folder or even general.py.

**Comment by glenn-jocher** [comment]
@kalenmike @173970984 `ultralytics.utils` renamed to `ultralytics.yolov5_utils` now in `ultralytics==0.0.17`. 

You can update your version with `pip install -U ultralytics`

**Comment by glenn-jocher** [comment]
@173970984 your original issue may now be resolved in `ultralytics==0.0.19`

Please update with `pip install -U ultralytics` and let us know if this resolves your issue!
