### ISSUE TITLE
Is it possible to upload a pretrained YOLOv5 model to HUB?

### ISSUE THREAD

**Issue by gdmcdonald** [ultralytics/hub#25]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

We have trained a model for wildlife species detection for 71 animal species in Australian national parks. Is it possible for us to upload this into the hub and use it there?

**Comment by kalenmike** [comment]
@gdmcdonald Thank you for your question.

Currently we do not have the option to upload an existing model. We are still in the process of developing the Ultralytics HUB and want to add the features that are most useful for our users. Would you please expand a little on your question so that we could have a better understanding of the feature you are requesting?

- Upload an existing model to the Ultralytics HUB in which format?
- Which of the features would you want to use? Inference? Exports?
- Is there anything else you would like to be able to do with your model once it has been uploaded?

Thank you for taking the time to raise a question, it is very helpful to have feedback so we can create a tool that is useful for your needs!

**Comment by gdmcdonald** [comment]
The current model is here on huggingface - 
https://huggingface.co/spaces/hlydecker/marsupial

Model weights here:
https://huggingface.co/spaces/hlydecker/marsupial/tree/main/model_weights

We really want to be able to do inference on large numbers of images -  in the order of 100k to 1M at a time.

**Comment by glenn-jocher** [comment]
@gdmcdonald can you send an email for us to better understand your use case? Thanks!

glenn.jocher@ultralytics.com
