### ISSUE TITLE
How to export model TensorFlow 

### ISSUE THREAD

**Issue by DenisOnline** [ultralytics/hub#253]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I am a student and I was given an assignment where I have to export TensorFlow, but it is not available to me( How do I get TensorFlow

**Comment by kalenmike** [comment]
@DenisOnline Thanks for asking the question. In order to export to TensorFlow you will need to train your model, once your model has been trained we support exports to several TensorFlow formats.

![image](https://user-images.githubusercontent.com/25989362/235863621-e92c63ab-06d2-4145-a431-de7b2b332dfd.png)
