### ISSUE TITLE
Camara not working on the app

### ISSUE THREAD

**Issue by MrShirker** [ultralytics/hub#257]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

It says you don't have permission to use the camera:
![Imagen de WhatsApp 2023-05-03 a las 20 16 36](https://user-images.githubusercontent.com/119264475/236009926-b3099ebc-7014-4aba-85b3-bed7bee96662.jpg)

But i gave it all the permissions
![Imagen de WhatsApp 2023-05-03 a las 20 25 07](https://user-images.githubusercontent.com/119264475/236009945-47a30167-530c-4875-8d6f-66f1e0fa650c.jpg)

I even reinstalled the app.

### Environment

Xiaomi Pro 10 Miui 14

**Comment by kalenmike** [comment]
@MrShirker Thanks for raising this bug. We noticed this bug with our latest version and have since rolled back to an earlier version. We are working on a fix, the solution for the moment is to delete the current app and download the previous version (the current version available in the store). This should allow you to grant permissions and use the app again.

**Comment by sergiossm** [comment]
@MrShirker Thank you for reporting. This issue is now solved in version 0.6.3
