### ISSUE TITLE
Problems using custom model with Pytorch

### ISSUE THREAD

**Issue by iRaiyz** [ultralytics/hub#27]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello,
I trained a model via Ultralytics Hub and a custom dataset that I uploaded. I am now looking to utilize the model via Pytorch or Tensorflow to predict images. I exported the model via Pytorch and Tensorflow saved model but I can't make it work. I tried the functions torch.load("path") but I keep obtaining the same error which is : ModuleNotFoundError: No module named 'models'.

Can you help me ? 

Thanks for reading me,
Adam.

**Comment by glenn-jocher** [comment]
@iRaiyz good question, I'll take a look.

**Comment by glenn-jocher** [comment]
@iRaiyz 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. PyTorch Hub inference with Ultralytics HUB models works correctly in my test just now:

<img width="1353" alt="Screen Shot 2022-05-05 at 1 46 06 PM" src="https://user-images.githubusercontent.com/26833433/167022841-f2ca74b7-1ac7-48e4-873a-07db70205697.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
