### ISSUE TITLE
iOS and android implementation code

### ISSUE THREAD

**Issue by Busterfake** [ultralytics/hub#276]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello, 
I have trained a yolov8n model with my own dataset and I am now trying to implement it into my apps (tflite and mlmodel). I have successfully tried it with the HUB app and I have to say the result are pretty amazing (only tested on iphone tho). 

I already have my app to implement my yolov5 mlmodel but the structure of the mlmodels between yolov5 and yolov8 is completly different and i didn't manage to make it work with yolov8. 

From what i saw the mlmodel exported on the HUB app is a FP16 Quantization with NMS added. 
I was wondering if it is possible to have the code that allows a such implementation of a mlmodel to make it work on my own app. 

Thank you so much for all your work !

**Comment by sergiossm** [comment]
Hi @Busterfake ,

Thank you for reaching out and sharing your positive experience. I'm glad to hear that you found the results amazing. 

Regarding your request for specific code or implementation details, I'm sorry, but we are unable to disclose that information. However, I would like to inform you that we offer licensing solutions for our mobile library.

If you are interested in exploring this option, please provide your contact information so that our team can get in touch with you. They will be able to discuss the details, pricing, and any specific licensing terms that may apply.

Once again, thank you for your interest in Ultralytics.
