### ISSUE TITLE
YOLOV8 in mobile Android and IOS

### ISSUE THREAD

**Issue by Dieguinho5** [ultralytics/hub#283]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi Ultralytics,
Congratulations on the development of YOLOV8. Sensational!

I have a doubt. What is the best way to run YOLOv8 on android and ios devices?

How does the ultralytics hub app run on android and ios?
I am interested in the fact that your app runs so well on android and ios that I would like to follow the same steps

Sorry, I searched a lot and didn't find enough material
Thanks

**Comment by sergiossm** [comment]
Hey @Dieguinho5, we're now offering a licensing solution for our mobile SDK 🚀. If you're interested, please fill in this form and we'll get back to you shortly https://ultralytics.com/license.

Simply put, our licensing solution provides access to a mobile SDK explicitly built for deploying YOLOv5 and YOLOv8 object detection, classification, and pose estimation models onto Android and iOS devices.

In order to deploy your own custom YOLOv8 models onto the SDK, you can go through the following steps:

1. Train your YOLOv8 model on your desired dataset
2. Convert the model into the corresponding format
3. Package the model file and include it in the SDK package
4. Use the SDK APIs to invoke the detection functions to run your custom Ultralytics YOLO model on the device

We hope this helps answer your question! If you have any more concerns or questions, please feel free to let us know.

**Comment by Dieguinho5** [comment]
eu converti para tflite conforme documentação usando a cli e não funcionou. Será que estou fazendo algo errado?
