### ISSUE TITLE
YOLOv8n Model Updated?

### ISSUE THREAD

**Issue by bortpro** [ultralytics/hub#302]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I trained a model with YOLOv8n a month ago and I was able to download the PyTorch model and convert it into a MyriadX blob use for downstream use successfully. However, when I am now training new YOLOv8n models, these are no longer being able to be converted into a MyriadX blob. 

2 questions:

1. Has there been some change in the YOLOv8n model training process on the Ultralytics Hub?
2. If so, is there a way for me to train models in the same YOLOv8n model as done a month ago? It is extremely time consuming to constantly update entire model pipelines if small parts of the pipeline update

**Comment by glenn-jocher** [comment]
@bortpro hi there! Yes we update and improve `ultralytics` on a daily basis, so without more information it's hard to say what the problem might be without a minimum reproducible example. Of course, you could always use HUB with an older version `ultralytics` as well if that was working for you in the past.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@bortpro yes there are constant improvements and changes to Ultralytics and YOLO. Since there are no errors here caused by Ultralytics workflows I would recommend you contact the authors of the package causing the error. 

Also it might help freezing dependencies to given package versions to ensure your workflow remains constant.

**Comment by bortpro** [comment]
@glenn-jocher The authors of the package were able to update according to the updates in Ultralytics YOLO. Is there a convenient way to freeze dependencies with Ultralytics, e.g. just pip installing a certain known working version of the python library ultralytics at the beginning of training a YOLO model?

**Comment by kalenmike** [comment]
@bortpro You can train a model using a pinned version of ultralytics by installing that specific version.

```bash
pip install ultralytics==8.0.120
```
