### ISSUE TITLE
I'm done with training but cannot deploy model on ultralytics hub why?

### ISSUE THREAD

**Issue by kosongdansatu** [ultralytics/hub#312]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

<img width="1440" alt="Screenshot 2023-06-26 at 06 42 30" src="https://github.com/ultralytics/hub/assets/92965442/49c46f01-d676-4ab9-b15b-188aaf6dde5c">
<img width="1436" alt="Screenshot 2023-06-26 at 06 42 17" src="https://github.com/ultralytics/hub/assets/92965442/3b2af05f-0f4c-4ec6-8540-bdd560dd7192">
<img width="1440" alt="Screenshot 2023-06-26 at 06 50 36" src="https://github.com/ultralytics/hub/assets/92965442/04857a2d-e4ae-4687-9165-b473492562b5">

I have a problem after finishing the training, I can't proceed to the next process, which is making the model and instead the results of the training dataset appear incomplete even though the training dataset page says it's finished. The same as trying to retrain but in Google Colabs a program error appears, is there a solution to overcome this so that I can get the Visdrone training model?

 I've been waiting 20 hours for this.

Thank you

**Comment by glenn-jocher** [comment]
@kosongdansatu thanks for the bug report! This is really strange. Does this occur with other datasets or only with VisDrone?

**Comment by kosongdansatu** [comment]
> thanks for the bug report! This is really strange. Does this occur with other datasets or only with VisDrone?

Incidentally, for now, I've just tried training data using only Visdrone, I don't know if other data has problems too

**Comment by kosongdansatu** [comment]
I'm waiting for fix this bug thanks

**Comment by glenn-jocher** [comment]
@kosongdansatu, thank you for raising an issue. We are sorry to hear that you have encountered a bug. We'll do our best to help you resolve the issue as soon as possible. 

In order to better understand the problem, could you please provide us with more information? 

1. Did you face this problem with other datasets or only with VisDrone?
2. Did you try to retrain the model by running the script again?
3. Could you please provide us with screenshots of the error message that appears in Google Colab?
4. Please ensure that you have followed the HUB Docs that explains the process of creating a dataset, training, and deploying the model on HUB. https://docs.ultralytics.com/hub/

Thank you for your patience and we'll do our best to help you overcome this issue.
