### ISSUE TITLE
Model to roboflow

### ISSUE THREAD

**Issue by MarkusMikkonen** [ultralytics/hub#319]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

It says that models will upload to roboflow automatically. I don't see the model in roboflow. I have set the api key for the project. Does it just take some time?

**Comment by glenn-jocher** [comment]
@MarkusMikkonen hi there! 

Thank you for reaching out to us with your question. When you upload a model to the Ultralytics HUB, it should automatically sync and appear in your [Roboflow](https://roboflow.com/) account.

However, please keep in mind that the synchronization process may take some time to complete. If you've already set the API key for the project and it has been a while since you uploaded the model, I would recommend waiting a bit longer to see if the model appears in Roboflow.

If you have any further questions or concerns, please don't hesitate to let us know. We're here to help you out!

**Comment by bllfoad** [comment]
I WAITED A LOT AND STILL NOT APPEARING THIS ALSO APPLY TO OTHER CREATED ACCOUNTS

**Comment by glenn-jocher** [comment]
@bllfoad thank you for your patience and for providing additional information. I apologize for any inconvenience you may have experienced.

Regarding the delay in your model appearing in Roboflow, it is unusual for the synchronization process to take so long. While there could be various reasons for this delay, I recommend reaching out to the Roboflow support team directly to investigate and resolve this issue.

Please contact Roboflow support and provide them with all relevant details, such as the API key, project information, and the specific model you are trying to sync. They will be best equipped to assist you in resolving the synchronization delay.

Feel free to let us know if you have any further questions or need any additional assistance. We are here to help!
