### ISSUE TITLE
Uploading private locally trained models in the HUB

### ISSUE THREAD

**Issue by 4nightmare** [ultralytics/hub#326]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi ,
I have several Yolov8 and v5 models trained on custom datasets and I was wondering if it is possible to directly upload them in the HUB so to use them with the smartphone?...this withouth uploading the different datasets and train again everything on the HUB

Thanks in advance.

**Comment by glenn-jocher** [comment]
@4nightmare hi,

Thank you for reaching out to us. Currently, the Ultralytics HUB does not support the direct upload of locally trained YOLOv8 and YOLOv5 models. In order to use your models with the Ultralytics HUB app on a smartphone, you would need to upload your datasets and train the models again on the HUB.

This is because the HUB requires the datasets to be available in order to generate predictions on the smartphone. By training the models on the HUB with your custom datasets, you ensure that the necessary data and model configurations are available for inference on the smartphone.

We understand that retraining models can be time-consuming, but the HUB offers a convenient and powerful platform for managing datasets and training models, helping streamline the process.

**Comment by 4nightmare** [comment]
Hi @glenn-jocher,
thank you for the quick reply.
I understand why the HUB works like that.
Hopefully (in the future) a dedicated fuction to upload locally trained models will be added.
thanks a lot for the moment.

**Comment by glenn-jocher** [comment]
Hello @4nightmare,

I'm glad to hear that you understand the current workings of the Ultralytics HUB. We are constantly striving to facilitate and enhance the workflows of our users.

Your suggestion to enable direct uploading of locally trained models is noted and appreciated. While we cannot promise immediate additions or changes, feedback like yours is definitely a driving force behind the continuous evolution of our platform.

Once again, thank you for your valuable input. We look forward to continuing to support your endeavours with Ultralytics HUB and its tools. We are grateful for your understanding and patience!
