### ISSUE TITLE
export pt file to engine file

### ISSUE THREAD

**Issue by angora0606** [ultralytics/hub#333]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I'm trying to export pt file to engine .It is worked but when working the this code "yolo task=detect mode=predict model=path/file.pt device=0" ,Im getting this error(" requirements: Ultralytics requirement ['onnxsim>=0.4.17'] not found, attempting AutoUpdate...).It still working and ı can take converted engine file but it happens in an un-optimized way.I think this is happening because of onnxsim.when I tried to install "pip install onnxsim", it was "ERROR: Could not build wheels for onnxsim, which is required to install pyproject.toml-based projects" I'm getting this error.
Im using Jetson Orin Nano.
Cuda:11.4
Python:3.8
L4T:35.3.1

**Comment by kalenmike** [comment]
@angora0606 Thanks for raising the question. I am not sure that I understand your problem completely can you please clarify some things.

Are you using Ultralytics HUB? _We do not currently support TensorRT exports from the Ultralytics HUB._

Did you export your PyTorch model yourself using the `ultralytics` package?

**Comment by angora0606** [comment]
I'm not using an ultralytics hub.This is exactly the github I use"https://github.com/ultralytics/ultralytics ".i'm trying to export, but "requirements: Ultralytics requirement ['onnxsim>=0.4.17'] not found, attempting AutoUpdate...)" I get an error in the form.I don't know how to handle it.

**Comment by kalenmike** [comment]
@angora0606 This our support repo for the Ultralytics HUB, please create your questions related to the ultralytics pacakge directly on that repository in the future.

To point you in the right direction you can try to install ultralytics with the export features and then attempt the export again:

`pip install -U ultralytics[export]`

Also your example code is for running inference not for exporting, to export you would need to run:

`yolo export format=engine model=model.pt device=0`

**Comment by angora0606** [comment]
pip install -U ultralytics[export] ı tried this code but it didnt work for me.Again ım getting same error.i know the export code, as you said, I didn't write the code to run the extraction, as you accidentally said last "yolo export format=engine model=model.pt device=0" I still get the same error when I run this code.

**Comment by glenn-jocher** [comment]
I apologize for the confusion, @angora0606. If you're encountering issues with the installation of the 'export' feature of `ultralytics`, it might be due to compatibility issues between your Python, CUDA, or Operating System versions and the `onnxsim` package, which is included in the `export` optional dependencies of `ultralytics`.

Detailed error logs would be beneficial in diagnosing the issue further, but I would suggest:

1. Attempt to update your pip version with `pip install --upgrade pip`, and then retry the `pip install -U ultralytics[export]`.

2. If the error persists, it would mean that `onnxsim` is failing to build on your system for some reason. You might need to troubleshoot this separately by trying to install `onnxsim` in a new python environment, or on a different system to check its compatibility.

Additionally, if you don't need to use ONNX simplification (which `onnxsim` provides), you could still run the export without installing the `export` features. You would get a non-simplified version of the ONNX model in such a case though.

Lastly, for support specific to the `ultralytics` package that's not related to Ultralytics HUB, it would be most effective to open an issue directly on the associated GitHub repo to get help tailored to that package from the developers who maintain it. The Ultralytics team is very responsive and will help you resolve the issue.
