### ISSUE TITLE
What is definition of ms and fps ?

### ISSUE THREAD

**Issue by rumjie** [ultralytics/hub#366]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, I am trying ultralytics hub app with my phone.
On real-time detection on camera, I can find ms and fps values and I would like to ask what this is exactly meaning. 

I can guess ms is for inference time for each images and fps is how many frames the model can infer at a second. 

However, with my phone, inference time for a image is 12~13 ms and fps is almost fixed with 30. 
With simple calculation 12 ms/frame is about 83 fps which is quite different with the value showed on display. Could you explain why this difference occurs?

**Comment by UltralyticsAssistant** [comment]
@rumjie hi there,

You're correct in your understanding. "ms" refers to milliseconds, indicating the inference time for each image. "fps" stands for frames per second, showing how many frames the model can process in a second.

The discrepancy you're noticing between the calculated fps (from ms/frame) and the displayed fps might be due to the additional operations that are performed apart from the model's inference. These additional operations can include image capturing, pre-processing, post-processing, displaying results on the screen, etc., all of which contribute to the total time taken for each frame but aren't included in the inference time (ms). The displayed fps takes into account the total time for all these operations for each frame.

So, even though your specific inference is taking around 12~13 ms, the total process per frame could require enough additional time to approximate to 30 frames per second. That's why you see the fps value around 30 on your phone's display.

Thank you for your question! If you have any more queries, don't hesitate to ask.
