### ISSUE TITLE
ultralyticsHUB Upload Dataset：The button is missing？

### ISSUE THREAD

**Issue by superCong** [ultralytics/hub#372]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

The button is missing？
<img width="814" alt="image" src="https://github.com/ultralytics/hub/assets/21659767/30f36276-1bf5-4f83-a871-6e82bfadd131">

**Comment by UltralyticsAssistant** [comment]
@superCong i'm sorry to hear that you're encountering issues with the Ultralytics HUB. In the case of the upload dataset button missing, this might be due to one of several reasons.

Firstly, please make sure you are logged in to your account. The dataset upload feature is only available to authenticated users.

Secondly, check whether the specific project that you're in has the necessary permissions for a dataset upload. Some projects might restrict certain actions based on user roles.

Lastly, there could be a temporary visual glitch or a rendering issue with the website. A simple refresh or reopening the page in the new browser tab could solve this problem.

If none of these solutions works, then it might be a bug that the developement team needs to look into. Thank you for raising this issue.

**Comment by kalenmike** [comment]
@superCong Thanks for raising this bug. We recently deployed a fix for this.
