### ISSUE TITLE
Public/Private tag error on mobile device

### ISSUE THREAD

**Issue by rumjie** [ultralytics/hub#373]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

![hub_error](https://github.com/ultralytics/hub/assets/103101268/1f97123c-78f2-421b-8e9d-5a856207631d)
   
On my phone (iphone 12) the list of datasets shows like this - _p1 testcase try_ is my own dataset, and rest of them are actually public. 
This is only on mobile environment, not in desktop.

**Comment by UltralyticsAssistant** [comment]
@rumjie thank you for bringing this to our attention. It appears you're experiencing a display error on the HUB when accessing it from a mobile device, which is causing some datasets to be incorrectly tagged.

The Ultralytics team strives to ensure a seamless user experience across all platforms, so we appreciate your report. We will investigate this issue and aim to resolve it as soon as possible. As part of that process, we may ask for further details if needed, so that we can fully understand and address the problem.

Please stay tuned for any updates on this issue, either through additional comments or a future update to the HUB platform. Thanks for your continued support and patience as we work on this issue.

**Comment by kalenmike** [comment]
@rumjie Can you please confirm the browser you are using and the URL you are navigating to? Also could you refresh your cache and reload the page.

**Comment by rumjie** [comment]
@kalenmike On my phone, I am using ultralytics hub app. I deleted and re-install it and the problem didn't solved. The project that I am handling is below: 
https://hub.ultralytics.com/projects/26uMTYNpqcrcjdIIQPVI
Please let me know you need additional information!

**Comment by kalenmike** [comment]
@rumjie Ok got you. Yes I have confirmed this bug in the current version of the HUB App. We are releasing a new version in the next few days that will address this. The app logic is swapped so private show as public and public show as private, but this does not affect your content.

**Comment by kalenmike** [comment]
This is resolved in the latest app.
