### ISSUE TITLE
yolov8 cannot show P， R，mAP

### ISSUE THREAD

**Issue by eggmakers** [ultralytics/hub#387]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

My yolov8 shows a warning when training the UA-DETRAC dataset: WARNING no labels found in detect set, can not compute metrics without labels, and the P, R, and mAP values are zero. My configuration is RTX4060, CuDA version 11.7, and python version 3.8
<img width="791" alt="屏幕截图 2023-09-09 151141" src="https://github.com/ultralytics/hub/assets/39152460/7eed9945-0c15-464f-9ce6-7ed04a30b520">

**Comment by UltralyticsAssistant** [comment]
@eggmakers it seems like the issue pertains to a lack of label data in your detect set. YOLOv8 is giving a warning because it can't find any labels in your detect set, so it can't compute the Precision, Recall, and mAP metrics. These metrics require ground truth labels for comparison with your model's predictions, to assess its performance.

You might want to re-check your dataset for any inconsistencies or errors in the label files. Be sure that any annotations correspond correctly to the images during training. It's also worth re-verifying if the path to your labels is directed correctly in your dataset.yaml file.

If you've recently changed, updated, or moved your data, it could have led to this issue. Always ensure you have the correct and full paths wherever your data is being accessed.

Let me know if this helps or if you have additional questions.
