### ISSUE TITLE
My inference results on pytorch model is 98% accurate, the model that i run on The mobile app fails to predict and always predict a single class for all other classes

### ISSUE THREAD

**Issue by nuhmanpk** [ultralytics/hub#400]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have trained a model on ultralytics hub and exported it to pt model. The inference results from the pt model is accurate. When i loaded the model on Ultralytics app from play Store the model predicts all class as same with high confidence. Can anyone explain what is the cause here, and how can I overcome the problem.

**Comment by UltralyticsAssistant** [comment]
@nuhmanpk hello, thanks for reaching out with your question. It's great to hear your model is working accurately with PyTorch.

When you see a discrepancy involving identical class predictions in different environments, there can be several possible causes. Below are few considerations that might help to resolve this issue:

1. Version mismatch: Ensure that the PyTorch version you used for training the model aligns with the one used in the Ultralytics App environment.

2. Preprocessing Input: Check whether the preprocessing steps applied to your input data in both environments are the same. Keep in mind that any difference in preprocessing can affect your results.

3. Model conversion: It's also possible that something may go astray during the conversion of your .pt model for the mobile app. Make sure the export and import steps were performed correctly.

To help us isolate the problem further, it would be beneficial if you could provide more information regarding how you exported and loaded your model into Ultralytics mobile app, and any error messages you may have encountered during the process. 

You may also wish to validate your model in other environments to see if the issue is specific to the mobile app or can be replicated elsewhere.
Let us know about any progress or if you have additional questions. Remember, the YOLO community and the Ultralytics team are always here to support you.

**Comment by jquaglia-uss** [comment]
are you training the model with images from your cell phone?

i've seen large performance drops myself once deploying to the app occasionally as well.

can you report out your train imgsz and inference imgsz?

**Comment by UltralyticsAssistant** [comment]
@jquaglia-uss hello, thanks for providing more details. To better understand the situation, you might want to take into consideration the following points:

1. Image Source: If you are using images from your cell phone for training, it could certainly lead to a performance drop when deploying to the app due to a difference in image quality or representation as compared to images in your training dataset.

2. Image Size: The image size you train on (`train imgsz`) and the size you use for inference (`inference imgsz`) could also be causing some discrepancies. If these sizes differ significantly, the model might not perform as expected. 

Having clarity on these aspects can help pinpoint potential sources of lower-than-expected performance. If there is a discrepancy in image sources or inconsistency in image sizes between training and inference, you would need to address those to get the expected output from your model.

Do let us know how you progress and if there are more questions we can assist with. Remember, the YOLO community and the Ultralytics team are here to assist anytime.
