### ISSUE TITLE
YOLOv5 Freezing on Raspberry Pi 3

### ISSUE THREAD

**Issue by rspandolfi** [ultralytics/hub#406]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

YOLOv5 used to run slow but fine on a Raspberry Pi 3. It still runs on a Pi 4 but is freezes on P 3 after:
VOLOv5 summary: 213 Layes, 7225885 parameters, 0 gradients
1/1: tcp://127.0.0.1:8888 ... Success (inf frames 1280x960 at 1.00 FPS)
Note that I am running YOLOv5 on a tcp stream a 1.00 FPS

**Comment by UltralyticsAssistant** [comment]
@rspandolfi the behavior you described could be due to insufficient memory or resources on your Raspberry Pi 3. YOLOv5 is a resource-intensive model and while it's designed to be as lightweight as possible, different versions of Raspberry Pi have varying capabilities.

The Raspberry Pi 3 may be struggling to allocate the necessary resources to run YOLOv5 robustly, especially if there are other processes drawing on its resources simultaneously. When this happens, the system may freeze as you've described.

You can check system resource usage on your Pi while running YOLOv5 to see if it's hitting its resource limits. Additionally, ensure your Raspberry Pi 3 OS is updated to its latest version and other software is not drawing on extensive resources concurrently. 

Lastly, you may want to consider using Raspberry Pi 4 for running YOLOv5 as you mentioned it is functioning well there, possibly due to its better hardware specs. 

You might find it useful to investigate the model optimization options provided by Ultralytics to help reduce resource consumption, such as quantization, pruning, etc., although such adjustments can slightly impact model accuracy.

**Comment by rspandolfi** [comment]
I always test on a new install and current operating system. This test was with the 64bit Raspberry Pi Operating System. After some additional investigation, I discovered the problem was with the version of PyTorch and Torchvision that are installed using your YOLOv5 installer:

cd ~/yolov5
sudo pip3 install -r requirements.txt

While this works just fine with a Raspberry Pi 4, these versions of PyTorch and Torchvision are not compatible with a Raspberry Pi 3. 

I corrected the problem by installing the correct version of PyTorch and Torchvision

sudo pip3 install torch==1.11.0
sudo pip3 install torchvision==0.12.0

Then YOLOv5 worked just fine on the Raspberry Pi 3 (although not as fast as with the Raspberry Pi 4).

**Comment by UltralyticsAssistant** [comment]
@rspandolfi thank you for sharing this solution! It's valuable to learn that adjusting the PyTorch and Torchvision versions made a difference in running YOLOv5 on the Raspberry Pi 3. The fact that these Python library versions can affect such compatibility issues is indeed an important insight.

It’s also good to consider the performance trade-off when using YOLOv5 on devices with differing compute powers, such as the Raspberry Pi 3 and Raspberry Pi 4. Going forward, users may need to adjust their version of PyTorch and Torchvision to match the capabilities of their hardware. 

We appreciate your diligence in both finding this solution and sharing it with the community! We recommend others facing related issues to use this method as a potential workaround. Remember, the YOLOv5 community always benefits from everyone's experiences and solutions.
