### ISSUE TITLE
Training process killed

### ISSUE THREAD

**Issue by jd1219** [ultralytics/hub#417]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

![photo1696211864](https://github.com/ultralytics/hub/assets/141599457/d7809a96-a17e-4e82-b55f-ba85e39d683f)
I am new to this ultralytics hub training, so i am using a device which CPU is AMD R7 5800H, 16GB memory and RTX 3050 GPU, then i trying to train YOLOv8x model as it is the most accurate model among the 5 models of YOLOv8, then it shows "KILLED" as the bar like the image above, whats the problem. I do trained a yolov8n model without any error, just for a better accuracy so i chose to try with yolov8x.

**Comment by UltralyticsAssistant** [comment]
@jd1219 hello and welcome to the Ultralytics community!

The "KILLED" message typically appears when training is prematurely ended due to an interruption. As for your case, the YOLOv8x model is much larger and more memory-intensive than the YOLOv8n model. The higher memory requirement of YOLOv8x could possibly exceed what your system can offer, especially given your RTX 3050 GPU and 16GB of memory. 

Training larger models like YOLOv8x may demand more GPU memory, and running out of this resource could cause the system to kill the process. Try reducing the batch size of your training process to lower GPU memory consumption. If this doesn't resolve your issue, you might consider utilizing a system with more memory capacity.

Should you continue to encounter problems, please provide more specific information such as your training configuration parameters, the precise training command you used, and your runtime environment, which will allow us to assist you more effectively.

Thank you for using Ultralytics HUB! We appreciate your understanding and patience as we work together towards solving this issue.

**Comment by Duskytechco** [comment]
I work together with JD and now we are facing the same problem ..


I ran YOLOv8x for 24hrs already but it showed finished on VS code but not on the website. Which is very disappointing as it was 24hrs. 

Could I have a deeper insight of what's happening.

**Comment by UltralyticsAssistant** [comment]
@Duskytechco hello, I'm sorry to hear about the difficulty you're experiencing. 

The inconsistency you noted between the status on VS Code and the website might be due to a synchronization issue. The Ultralytics HUB synchronizes the real-time status of the training process, but sometimes, due to network interruptions or system configuration on a specific user's machine, some synchronization issues might occur.

We recommend checking to ensure that your internet connection remains stable during the training, and also the VS Code plugin stays on during the entire training process, as any disconnection may interrupt the synchronization process.

Finally, please make sure that your Ultralytics account used within VS Code is the same one you are checking the status on Ultralytics HUB. If you're still encountering the issue after checking these suggestions, providing more detailed information can help us better understand the situation. 

Thank you for your patience and for using Ultralytics HUB.

**Comment by kalenmike** [comment]
@Duskytechco I might be able to help if you still cannot see your model in HUB? Share your model id with me and I will look into it.

**Comment by jd1219** [comment]
> @Duskytechco I might be able to help if you still cannot see your model in HUB? Share your model id with me and I will look into it.

its okay, we use the google colab to train it, and successfully have our model now, thanks

**Comment by UltralyticsAssistant** [comment]
@jd1219 I'm glad to hear that the issue has been resolved and you've successfully trained your model using Google Colab. It's essential to have alternative solutions, especially when encountering challenges. If you have future questions or encounter anything else while using Ultralytics HUB, don't hesitate to ask. Enjoy your journey in model training with Ultralytics!
