### ISSUE TITLE
Bounding Boxes Stay on Screen

### ISSUE THREAD

**Issue by camillediagnoly** [ultralytics/hub#421]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

![Screenshot_samsungS8](https://github.com/ultralytics/hub/assets/108474783/95e99006-3b28-49b5-a6c8-53b90925e8ab)

I am unsure whether this is the right repository for this issue:

I would like to try out different YOLO models using the Ultralytics HUB application available on Play Store on Android. My hardware is Samsung Galaxy Tab S8 and Samsung Galaxy Tab S9. However, the boxes displayed on the camera video stream seem random, whatever the selected model is (I have tried  YOLOv8n, YOLOv8s, YOLOv5lu, YOLOv5n6u), as shown in the attached screenshot.

The application is otherwise really great and works on some other devices I tried!

### Environment

- Hardware: Galaxy Tab S8 (also tried on Galaxy Tab S9)
- RAM: 8Gb
- Processor: Qualcomm SM8450 Snapdragon 8 Gen 1
- Android Version: 13
- Application downloaded on Google Play in 10/2023

### Minimal Reproducible Example

1. Download the Ultralytics HUB on Samsung Galaxy Tab S8 or S9
2. Run the default model on the Predict tab

**Comment by UltralyticsAssistant** [comment]
@camillediagnoly thank you for raising this issue and providing detailed information about your hardware environment and the steps to reproduce the issue. It greatly helps in diagnosing the problem.

From your description, it seems like you're experiencing difficulties using the Ultralytics HUB application on Samsung Galaxy Tab S8 and S9. You mentioned that the displayed bounding boxes on the camera video stream appear random, regardless of the YOLO model used (YOLOv8n, YOLOv8s, YOLOv5lu, YOLOv5n6u).

First of all, I'd recommend to ensure that your devices' operating systems are up to date. If the problem persists, it could be due to device-specific issues or possibly some incompatibility between the Ultralytics HUB application and your particular Android version or device model.

We will investigate this issue further and work on a solution. Rest assured, our team is dedicated to improving our Android app's compatibility across all devices. We appreciate your understanding and patience as we work to resolve this issue.

P.S. Thank you for your kind words about our application! The credit goes to the amazing YOLO and Ultralytics community who constantly contribute to its betterment and towards making computer vision technology more accessible.

**Comment by camillediagnoly** [comment]
Thank you for your quick reply! The device's operating system is indeed up to date, so the problem must come from somewhere else, probably a hardware-specific issue as you said.

**Comment by sergiossm** [comment]
Hey @camillediagnoly never mind the previous reply. We are aware that inference on certain Android tablet devices might not work correctly. Have you had the opportunity to test the app on a mobile device?
