### ISSUE TITLE
iOS App does not open custom model anymore

### ISSUE THREAD

**Issue by Joyphish** [ultralytics/hub#423]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

The updates iOS app can not open custom models any more. When Project or Dataset icons are clicked, the app keeps spinning and never show the content. I can’t add custom models like I did in previous versions. 

### Environment

iOS

**Comment by UltralyticsAssistant** [comment]
@Joyphish i'm sorry to hear about the issue you've encountered with the latest iOS app version. The problem with the app not loading content when clicking on Project or Dataset icons is indeed troublesome. Also not being able to add custom models as you did in previous versions is something that shouldn't be happening.

We understand this can impede productivity, and our development team will begin troubleshooting based on the data you provided. We'll look into the problem with the looping spinner and why the new version isn't behaving as previous ones did with regard to adding custom models. 

Thank you for bringing this to our attention. Your feedback is vital in helping us improve the Ultralytics ecosystem. We appreciate your patience and hope to resolve this issue promptly.

Once the fix is implemented, it will be pushed in an upcoming update. We'll notify you once it's available. In the meantime, please keep up to date with the latest releases and notes on our GitHub page.
