### ISSUE TITLE
Been stuck on upload and invalid yaml format errors for the past 10 hrs

### ISSUE THREAD

**Issue by Glenmk** [ultralytics/hub#429]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

One of the primary issues was the way in which the data within the dataset was arranged. So I took my dataset and arranged it in the recommended way such that:
dataset:
images:
 train: /dataset/images/train
 Val: /dataset/images/val
 test: /dataset/images/test
labels:
 train: /dataset/labels/train
 Val: /dataset/lables/val
 test: /dataset/lables/test

Note that the above is just the structure of my directory and not an actual YAML file.
Then I structured my YAML file in the way it has been recommended on the template. But even then my upload either failed or restart to 0% after 100%

### Environment

-Computer:Windows 10
-Google Chrome browser 

### Minimal Reproducible Example

Create a YAML file using this code snippet.

import os
import yaml

# Define the dataset information
dataset_info = {
    'dataset': {
        'images': {
            'train': '/dataset/images/train', 
            'val': '/dataset/images/val',
            'test': '/dataset/images/test'
        },
        'labels': {
            'train': '/dataset/labels/train',
            'val': '/dataset/labels/val',
            'test': '/dataset/labels/test'
        }
    },
    'nc': 4,  # Number of classes
    'names': ['buffalo', 'elephant', 'rhino', 'zebra']  # List of class names
}

# Specify the YAML file path
yaml_file_path = 'dataset_info.yaml'

# Write the dataset information to the YAML file
with open(yaml_file_path, 'w') as yaml_file:
    yaml.dump(dataset_info, yaml_file, default_flow_style=False)

print(f'YAML file created: {yaml_file_path}')

### Additional

Nothing else to share. Otherwise Ultralytics is a game changer for fellow CNN enthusiasts.

**Comment by UltralyticsAssistant** [comment]
@Glenmk i'm sorry to hear about the trouble you're facing and definitely understand how frustrating it can be when uploads are not successful. Firstly, thank you for giving a detailed account of the issue, it is extremely beneficial in understanding the problem better.

From the structure and YAML code you've shared, everything seems to be correctly formatted. Your dataset directory structure and accompanying YAML file appear to be as recommended. Nonetheless, it is essential to make sure that the paths mentioned in the YAML file are absolutely correct and the necessary image and label files exist in the specified directories.

One common mistake often made is not including the file extension while specifying the path. Be sure to check that you're including the '.jpg' (or any other image file extension applicable) at the end of your image file paths and '.txt' (YOLO format) for your label file paths in your dataset.

Regarding the upload reset issue, this can sometimes occur due to network instability or browser-related issues. Here are a few things you can try:

1. You can ensure network stability. If the internet connection is frequently disconnecting or unstable, it could cause upload issues.

2. Try to clear your browser cache or try using a different browser.

3. Sometimes, using the private or incognito mode of your browser can also help.

Lastly, thank you for your kind words regarding Ultralytics. We're glad to hear that you find our work valuable. Remember, it's hardworking contributors and enthusiasts like you who really make the difference in the community!

**Comment by kalenmike** [comment]
@Glenmk Did you manage to get this resolved? We have the demo dataset in this repo that should help with the structure.

**Comment by Glenmk** [comment]
No actually I used the same dataset but in a format compatible to YOLOv8 at
first. Everything was going well, the upload was complete and I was now
training the model but then I got an error message when the program was
running epoch 99. And that's what started this whole ordeal. So because of
time limit, I opted to using a YOLOv5 model instead and the training went
smoothly and quicker just that the model Isn't as accurate as I wanted it
to be. The dataset has 1500 images of 29 classes I believe. And I had
redownloaded it in a format compatible with YOLOv5 on the second attempt.

**Comment by kalenmike** [comment]
@Glenmk Ok thanks for the detailed response. We are working on the resume bug you experienced [here](https://github.com/ultralytics/hub/issues/461). I will close this issue for now, please feel free to create another if you have any more issues.

**Comment by Glenmk** [comment]
Thank you. I just realized I have been replying a different issue. But
thank you for your patience.

**Comment by UltralyticsAssistant** [comment]
No worries at all, @Glenmk. It can happen easily, especially when managing multiple issues or conversations. I'm glad I could assist you today, and please remember you can always reach out with any further questions or issues you may encounter. We appreciate your input and patience throughout this process. Best of luck with your future projects, and I hope your next experience with YOLOv8 will be smoother. Have a great day!
