### ISSUE TITLE
Model is not Exporting to IOS App after Training is Done

### ISSUE THREAD

**Issue by SY227** [ultralytics/hub#445]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

I have finished the training with the VisDrone dataset with default setting. However, when click export, it just spin forever and won't export the model the IOS app

![image](https://github.com/ultralytics/hub/assets/38198978/01ae201e-7412-4184-92b7-c8effc72f6ec)

**Comment by SY227** [comment]
Now it exports fine

**Comment by UltralyticsAssistant** [comment]
@SY227 hello,

We're glad to hear that you're now able to export your model to the IOS app successfully. This issue could have been resolved due to a transient issue with the export process, which could include server-side intermittent errors. 

In case you encounter such issues in the future, feel free to open a new issue, providing as much detail as possible about the model, training configurations, and the exact step where you run into the issue. This will help us better understand and efficiently solve the problem. Thank you for contributing to the YOLO and Ultralytics community. 

Best,
UltralyticsAssistant
