### ISSUE TITLE
Cannot Deploy Model After Resuming

### ISSUE THREAD

**Issue by choibyeongyeong** [ultralytics/hub#447]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! I am a pro user who is actively using ultralytics.
I'm facing an issue and need your help.

Training environment: Google Colab
Condition: 320p * 320p input image
Model: yolov8

Training has been completed 100%, but deployment is not happening. It is stuck at "estimating...".
How can I solve this issue? 
Thank you for your response.

**Comment by choibyeongyeong** [comment]
Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/100      9.15G     0.4762     0.2421      0.848         54        320: 100%|██████████| 118/118 [01:32<00:00,  1.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 6/6 [00:06<00:00,  1.01s/it]
                   all        955       1419      0.665      0.704      0.699      0.533

33 epochs completed in 0.940 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 52.0MB
Ultralytics HUB: Syncing final model...
Ultralytics HUB: WARNING ⚠️ Model upload issue. Missing model runs/detect/train/weights/best.pt.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-2-8b6706470ad4>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 model = YOLO('https://hub.ultralytics.com/models/J8QuyngKHIrZFHwTXWm8')
----> 4 model.train()

6 frames
[/usr/lib/python3.10/pathlib.py](https://localhost:8080/#) in stat(self, follow_symlinks)
   1095         os.stat() does.
   1096         """
-> 1097         return self._accessor.stat(self, follow_symlinks=follow_symlinks)
   1098 
   1099     def owner(self):

FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt

**Comment by UltralyticsAssistant** [comment]
@choibyeongyeong based on the error log you've provided, it seems like the model you are trying to deploy cannot find the 'best.pt' weights file in the specified directory, which possibly is a result of it not being saved correctly after training.

Here are a few suggestions:

1. **Check the save directory**: Ensure that the training weights are actually being saved in the 'runs/detect/train/weights/' directory. Check the spelling and the hierarchy of your directories.

2. **Verify weights saving**: Ultralytics YOLO typically saves the 'last.pt' and the 'best.pt' files after training. The 'best.pt' is saved when the model achieves the best validation performance. If the 'best.pt' file is not found, this could mean that your model hasn't improved on the validation set after a save point. Monitor your validation metrics to confirm this.

3. **Compare with 'last.pt'**: You mentioned that the optimizer is being stripped from 'last.pt', which indicates that 'last.pt' is being successfully saved. Comparing the saving processes of 'last.pt' and 'best.pt' might provide insights about what's going wrong.

4. **File permissions**: Depending on your environment, there may be file permissions to take into account. Ensure that your script has the necessary permissions to write into the folder where the .pt file should be saved.

Remember, the Ultralytics GitHub repo is governed by the AGPL-3.0 License which allows you to modify and use the code with certain conditions, so you're free to troubleshoot and modify as necessary. If none of these suggestions work, feel free to provide more information and we'll further assist you!

**Comment by markatlarge** [comment]
I had this same issue using the HUB.  How would I go about trouble shooting it in that case.

**Comment by UltralyticsAssistant** [comment]
@markatlarge apologies for the confusion earlier. If the issue occurred while using the Ultralytics HUB for model deployment, this could be indicative of an internal issue with the HUB service. Here are steps you can take to troubleshoot this problem:

1. **Model Check**: First, confirm that the 'best.pt' model file has been generated and is present in the correct location within your working directory on Google Colab.

2. **HUB Sync**: Make sure that the sync command is correctly pointing to the directory where the 'best.pt' file is located. Any discrepancy in the file path can cause the file not to be found.

3. **Retry Deployment**: Sometimes, transient network issues or service interruptions can cause the deployment to fail. Attempting again may resolve the issue if it was caused by a temporary glitch.

4. **Inspect HUB Logs**: If the HUB provides any logs or console outputs during the attempted deployment, inspect these for any additional error messages or warnings that can guide you to the source of the problem.

5. **Contact Support**: If the above steps don't resolve the issue, you should consider reaching out for support. The Ultralytics HUB team can assist with service-specific issues and potentially diagnose the problem from the server-side.

In the case that you need to report this issue, provide as much information as possible to the support team, including detailed steps to reproduce the problem, any error messages, and what you have tried so far to resolve it. This will help the support team understand and address your issue more quickly. For detailed guidelines on how to use the Ultralytics HUB for model training and deployment, you can refer to the documentation provided by Ultralytics.

**Comment by kalenmike** [comment]
@choibyeongyeong It looks like this is related to the resume issue reported here:

https://github.com/ultralytics/hub/issues/461

We are currently looking into a fix for this. For the moment we can force a correction on a specific model if you can provide me with your model id. This can be found in the URL.
