### ISSUE TITLE
Roboflow dataset always showing loading indicator ?

### ISSUE THREAD

**Issue by zubairghori** [ultralytics/hub#455]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Roboflow dataset always showing loading indicator ?
<img width="1512" alt="Screenshot 2023-11-03 at 4 05 45 AM" src="https://github.com/ultralytics/hub/assets/8655968/dad44389-603e-4991-be16-937ef92a8be6">

**Comment by UltralyticsAssistant** [comment]
@zubairghori hello,

Thank you for informing us about this issue, we appreciate your input. The persistent loading indicator you are seeing could be due to a few reasons:

1. Network Connection: It might be a network connectivity issue. In such cases, retrying after a while usually resolves the problem.
2. Incorrect Dataset: The dataset URL or key you are using might not be correct, causing the HUB to keep trying to load it indefinitely.
3. Server-side issue: It could also be a problem on our end, in which case our technical team would need to investigate the issue.

We will need more information to get a clearer picture of your situation. Could you provide us with the steps you've taken prior to the problem appearing, and any relevant symptoms or details that you've noticed?

Your feedback is invaluable to help us continually improve the Ultralytics HUB experience. Our technical team will look into the issue and respond promptly.

Thank you for your patience and support.

**Comment by kalenmike** [comment]
@zubairghori Is this a Roboflow dataset that was already added to your account or one that you are trying to import?
