### ISSUE TITLE
Cannot Complete Training After Resuming

### ISSUE THREAD

**Issue by spielbrecher** [ultralytics/hub#461]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I've trained model for 100%, but it saved only 86 epoch checkpoint. I've restarted again and now its 91 epoch and still 86 epoch checkpoint saved. But I can see graphics on page model by 100 epochs! I can't export model without finish training. How can I fix the problem?

**Comment by UltralyticsAssistant** [comment]
@spielbrecher hello there!

Thank you for reaching out with details about the issue you're encountering during your model training. It seems there's a discrepancy between the epochs reported by the training progress and the checkpoints being saved. Usually, a new checkpoint should be saved at regular intervals or after certain epochs have been completed.

Considering the graphics page displays results for 100 epochs, it's reassuring that the model has indeed completed the training. However, the checkpoints not updating beyond the 86th epoch is unusual. Let's try to troubleshoot the issue:

1. Ensure the training session has enough resources to run without interruptions and is allowed to save new files (check disk space and permissions).
2. Have a look at the training logs for any errors or warnings that occurred after epoch 86—these messages could provide valuable insights into why later checkpoints are not being saved.
3. Verify the configuration settings for checkpoint saving intervals to see if there has been any customization that might be affecting the expected behavior.
4. If your model's progress graphics indicate that the model has learned adequately by epoch 86, consider utilizing the last saved checkpoint to export your model. This could be especially relevant if the subsequent epochs have not resulted in significant improvements.

Should none of these steps identify or solve the problem, it might be worth considering reaching out for further assistance with detailed information about your specific setup. You may also attempt to manually trigger a checkpoint save, but without including code, I'll guide you towards checking the training scripts' section responsible for checkpoints to ensure it's operating correctly.

We appreciate your cooperation and patience as we aim to resolve this matter. Best of luck with your model training, and I'm here to assist you further if needed!
