### ISSUE TITLE
Download of Models not working on iOS 

### ISSUE THREAD

**Issue by krilezr** [ultralytics/hub#463]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

After the model was successfully trained, it was not possible to download the custom model. The message "downloading 0%" is showing but no progress. 
Later in the list it shows that the Model is Exported but cannot be used

### Environment

IOS 17
Iphone 13

**Comment by UltralyticsAssistant** [comment]
@krilezr hello,

Thank you for reporting this issue with downloading models on iOS, and I apologize for the inconvenience you're experiencing.

To help resolve this problem, please try the following steps:

1. Close and restart the HUB app on your device.
2. Ensure that you have a stable internet connection. Sometimes, connectivity issues can hinder the download process.
3. Check if there's enough storage space available on your iPhone to accommodate the model file.
4. If the issue persists, try to download the model using another device or a computer to pinpoint if the problem is specific to your iOS environment.

If none of these steps work, please provide any error messages or screenshots that could help us understand the issue better. We'll investigate the matter further and look for a solution.

For detailed guidance, please refer to our Ultralytics HUB documentation, which might also have specific instructions and answers to common issues related to model export and download.

Please let us know the outcome after trying the suggested steps, as your feedback is valuable in improving the HUB experience for all users.

Thank you for your collaboration, and we're looking forward to helping you get the most out of Ultralytics HUB.

**Comment by kalenmike** [comment]
@krilezr Could you provide us with the model id so that we can investigate this further? You can find this in the URL.
