### ISSUE TITLE
Not able to upload my model in the IOS app

### ISSUE THREAD

**Issue by cayorodriguez** [ultralytics/hub#470]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have a model to detect other aircraft in flight and need to test it under realistic conditions in my plane using the ultralytics app. Currently I am unable to upload it. This is the model:
https://hub.ultralytics.com/models/P31gsbfGgzoBetNqPwvW
I am using an iphone 15.
I
Thanks

Carlos

### Additional

 believe that this aplication could enhance safety, and I am planning to offer the model for free.

**Comment by UltralyticsAssistant** [comment]
@cayorodriguez hello Carlos,

Thank you for reaching out and for your interest in using the Ultralytics app to deploy your model. I apologize for the inconvenience you're experiencing with uploading your model.

To address the issue, let's make sure that all necessary steps are followed:
1. Ensure that the model is exported in the correct format expected by the Ultralytics iOS app.
2. Verify that the model size does not exceed any limits set by the app.
3. Make sure that your iPhone is running a compatible iOS version that supports the app.
4. Check that you have a stable internet connection during the upload process.

Since you've already searched through the issues and discussions, it might help to review the documentation for any specific instructions or requirements related to uploading models to the iOS app. Please visit the Ultralytics HUB Docs for detailed guidance.

If after reviewing the documentation your issue persists, it would be helpful to provide specific details about the error messages or issues you encounter during the upload process. This will help us to troubleshoot the problem more effectively.

Thank you for considering to offer your model for free to enhance safety. We value contributions to the community and are here to support your efforts to test and deploy your model. If you have any more questions or require further assistance, please do not hesitate to reach out.

**Comment by kalenmike** [comment]
@cayorodriguez Thank you taking the time to raise this. Can you give us some more information.

Are you able to see your model in the app?
Are you able to select the model in the app, but inference is not working?

**Comment by cayorodriguez** [comment]
I am not seeing the model in the app

==============
Carlos Rodriguez
==============

**Comment by kalenmike** [comment]
@cayorodriguez Thanks for the update. Would you please share your model id here so that we can look into what is going wrong? You can find this in the URL on the web version of HUB.

Also just to confirm, you have logged into the app with the same account that you are using on the web?

**Comment by cayorodriguez** [comment]
This is the model:
https://hub.ultralytics.com/models/P31gsbfGgzoBetNqPwvW


I have trained another one since. Still not showing.
Niw it shows but is asking me to download it to the app...

How do I do that?


And I am using the same account linked to this email, since I am using the
login through Google.

**Comment by kalenmike** [comment]
@cayorodriguez Your web content should show up in the app automatically after you have logged in. I have attached a screenshot.

1. Log into the app
2. Click on the projects icon in the bottom navigation
3. Change to the Private or Unlisted tab on the top just under Projects.
4. Open the project that contains your model.

Please let me know if after following these steps you still cannot see your custom projects and models.

1. Once you see your models you have the option to export them into the app format if not already done.
2. You can then download them to your device. 
3. Once download click the heart button to add them to your available inference models.
4. One saved to your favorites you can click the Predict icon and swipe along your available models then select the one you want to activate.

![image](https://github.com/ultralytics/hub/assets/25989362/9a3499b5-6ed1-44f7-b05c-8973d1659b30)

**Comment by cayorodriguez** [comment]
I logged out and logged in again as ***@***.***

It shows in the predict window but tells me to download it first

But it is not appearing in private or unlisted
I can't download it

**Comment by cayorodriguez** [comment]
I was able to load my mother thank you

**Comment by UltralyticsAssistant** [comment]
@cayorodriguez That's great to hear, Carlos! I'm glad to know that your model is now successfully loaded. If you have any further questions or if there's anything else we can assist you with, please don't hesitate to reach out. Wishing you all the best with your in-flight aircraft detection model, and thank you for your valuable contribution to safety and the community.
