### ISSUE TITLE
Problem uploading Pose dataset

### ISSUE THREAD

**Issue by naruto553** [ultralytics/hub#484]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When I upload Pose dataset to Ultralytics HUB, I get "Unable to process the dataset." What are the possible reasons for this error?

**Comment by UltralyticsAssistant** [comment]
@naruto553 hi there 👋,

Thank you for reaching out! I'm sorry to hear you're experiencing difficulty uploading your Pose dataset to the Ultralytics HUB.

The "Unable to process the dataset" error can occur for a few reasons:

1. **Format Mismatch**: Ensure the dataset is in a supported format (e.g., COCO format for pose estimation). The directory structure and annotation files need to be consistent with the expected format.

2. **File Size Issues**: The dataset files may be too large, causing an upload timeout or memory issue.

3. **Corrupt Files**: Occasionally, if there are corrupt images or annotation files, the system might not be able to process them.

4. **Server Side Glitches**: Sometimes, the problem could be a transient issue with the HUB server itself.

To resolve this, you can:

- Double-check the dataset format and ensure it adheres to the required standards detailed in our documentation.
- Attempt uploading a smaller subset of the dataset to identify if the issue is file-specific or size-related.
- Try to re-upload the dataset after some time in case it was a temporary server glitch.

If the issue persists, please provide us with the following additional information for further diagnosis:
- The file type and structure of your dataset.
- The size of the dataset you are trying to upload.
- Any error messages or logs that you see when the upload fails.

We are here to assist you, and your success with the Ultralytics HUB is our priority! 🌟

Don't hesitate to reach out if you have any additional questions or need further assistance.

**Comment by kalenmike** [comment]
@naruto553 Can you share a link to your dataset for review?

**Comment by naruto553** [comment]
Solved this issue. The cause was that the one of the image files had a empty annotation data. 

I was trying to deploy pose model and found out Pose detection is not available on iOS app. When do you plan to release the feature?

**Comment by pderrenger** [comment]
Hi @naruto553, great to hear you solved the issue with the dataset! 🎉

Regarding pose detection on the iOS app, we are continually working on expanding the functionalities of our tools, including mobile support. However, I can't provide a specific timeline for the release of the pose detection feature on iOS at the moment.

Stay tuned for updates, and thanks for your interest and support in making our tools better! If you have any more questions or suggestions, feel free to share.
