### ISSUE TITLE
No Storage Available

### ISSUE THREAD

**Issue by waylonflinn** [ultralytics/hub#49]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

When uploading a dataset, upload fails with the error "No Storage Available".

This happens even after deleting all my datasets and all models save one then trying to re-upload a dataset that previously worked.

Additionally my dashboard shows 177.3 GB / 100.0 GB for Storage Used. I currently have zero datasets uploaded and a single model that lists its size as 146 MB.

![ultralytics-dashboard](https://user-images.githubusercontent.com/804108/175394532-6d66071c-8c79-4e98-80b6-4fa4a2f06f29.png)

### Environment

Linux (Arch)
Brave

### Minimal Reproducible Example

1. Login to my Hub account
2. Try to upload a dataset
3. Get incorrect storage used numbers and an error message mentioning "No Storage"

**Comment by kalenmike** [comment]
@waylonflinn We will take a look and see what is happening with your account.

**Comment by kalenmike** [comment]
@waylonflinn Thanks for raising this issue, the data in your account is not hard deleted immediately after you delete in in Ultralytics HUB. The records are soft deleted and the data enters into a queue where it waits for deletion. I can see that you trained several models and the checkpoints are what are using up all of your storage.

We will work on improving this process to prevent similar issues in the future. For now I have moved your deletions to the top of the queue to be processed., this will free up space on your account.

Please let me know if you have any further issues.

**Comment by glenn-jocher** [comment]
@kalenmike @stefani-kovachevska trash can feature should resolve this in the future, i.e. Google Drive trash can also uses storage unless emptied.

@kalenmike we are overwriting checkpoints on save right, i.e. during training we should have 2 checkpoints saved (best.pt and last.pt), and then after training completes we should just be storing the final best.pt

**Comment by kalenmike** [comment]
@glenn-jocher No checkpoints are not currently overridden. I am trying to schedule a meeting with you and Sergio for today to discuss these issues.

**Comment by waylonflinn** [comment]
Thanks for the response.

To better inform your discussion, it's 4 hours later and I have the following in my account:
* 1 project
* 1 model
* 0 datasets

Here's what my reported usage looks like right now:

Dashboard reports 85.2 GB used
![ultralytics-dashboard-02](https://user-images.githubusercontent.com/804108/175560200-219201e4-c525-442a-bf23-a6a06c1d1795.png)

Project page reports 463.8 MB used (top project is the included default project)
![ultralytics-dashboard-03](https://user-images.githubusercontent.com/804108/175560681-d03de629-21fb-42f2-9e02-849f6192e55b.png)

Model page reports 146 MB used
![ultralytics-dashboard-04](https://user-images.githubusercontent.com/804108/175560863-4f60d785-c379-4cba-a7bd-34e9225b858c.png)

To give you some sense of how your users might perceive this: 

At best I consider this a very poor user experience. At worst it is a complete deal breaker for active use of your platform.

The combination of factors contributing to this make it almost impossible to manage usage of the single limited resource. I was actively using the HUB (despite other bugs and annoyances) but was forced to abandon it in favor of local training because of this set of circumstances. This is likely the opposite of the scenarios that lead to the growth you're hoping for.

You might think that non-free accounts with higher caps would mitigate this. I suggest the opposite. If I'm paying for more space, I would be infuriated to encounter this sort of thing when I got close to the paid cap. With my free account I'm merely disappointed and annoyed. It is free after all.

Thanks for putting in the work to create something that's already very useful and could be a great tool in the future. I hope this information is encouraging and helpful.

**Comment by kalenmike** [comment]
@waylonflinn Thank you for taking the time to send us your detailed feedback. The Ultralytics HUB is currently in beta and we are extremely grateful to have users like you provide us with feedback so that we may improve the user experience.

Since you first raised this issue the development team have had a meeting and we have begun implementing several improvement to the Ultralytics HUB.

1. Previously a checkpoint was saved against the users data for each epoch. We are now only saving the latest checkpoints. These changes are now live. _In your case as you were training YOLOv5l6 it resulted in a 500MB file for each epoch which is the reason for the unaccounted for storage. Previously you had 150 epochs at around 500MB each. If you review your account since this update you will see significantly less usage._ 
2. We have begun work on a 'trash can' type of feature where you will be able to force that your data marked for deletion is immediately deleted.

I can see how the UI can make understanding your usage difficult and we will work on improving this. Currently the Project page will show the total storage use of all exported models including PyTorch. While the models view only shows the size of the PyTorch file.

I hope that the changes we implemented today will improve you experience and thank you again for helping us improve this tool.

**Comment by waylonflinn** [comment]
Much better. Thank you!

![ultralytics-dashboard-05](https://user-images.githubusercontent.com/804108/175658690-c5b6f5f3-f780-47b9-8ca8-e8ba679af746.png)

**Comment by glenn-jocher** [comment]
@waylonflinn thanks for the critical feedback, this is very valuable to us. We share your frustrations with the opaqueness of the storage calculations and are working to resolve these issues ASAP. The main changes in our roadmap are here, but please let us know if you have alternate suggestions on this topic or any other!

1. Removing individual epoch checkpoints (implemented above). This should have been removed previously and remained in place due to an internal miscommunication.
2. Adding a trash can with file browser to help users see (and permanently delete) individual models/datasets/projects.
3. Future Pro/Enterprise plans with higher/unlimited storage ceilings.
