### ISSUE TITLE
Not able to resume training

### ISSUE THREAD

**Issue by VarunNelakanti** [ultralytics/hub#493]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I was training a model, and due to some error in Google Collab when it ran out of RAM memory, it stopped running. I tried to restart the training, but it always throws the error which I'm attaching in the issue. 
<img width="2056" alt="Screenshot 2023-12-11 at 19 55 02" src="https://github.com/ultralytics/hub/assets/32270482/c3dd00f7-192c-474f-a54f-48b812dfd908">

As you can see, there is a shape error and I do not understand why it is happening. It has trained till 79th epoch, and it does not resume training. Any help will be useful.

### Environment

-Google Collab, Ultralytics

### Minimal Reproducible Example

1. Start a custom segmentation training on Yolov8
2. Stop the training
3. Restart the training

**Comment by VarunNelakanti** [comment]
Also, no changes have been made to either the model or the data. Tried to restart the training within 5 mins of it crashing.

**Comment by UltralyticsAssistant** [comment]
@VarunNelakanti hello! I'm sorry to hear that you're having trouble resuming your training.

The error screenshot suggests there's a mismatch between the expected shape of certain data and the shape of data being received during training, which commonly arises from discrepancies in dataset or checkpoint structure.

It's possible that the abrupt interruption caused some inconsistencies in the training state. Here are a few steps to check:

1. Verify that the checkpoint file has not been corrupted. Check if its file size looks reasonable compared to other checkpoints.
2. Ensure the dataset is correctly set up and accessible, with no changes to file paths or structures after the crash.
3. Confirm that the configurations (hyperparameters, model architecture) used to resume training are the same as those used initially.
4. If possible, try to resume with a slightly earlier checkpoint to see if the most recent one is the issue.

Remember to check the Ultralytics HUB Docs for further guidance on resuming training processes. If you've gone through these steps and the issue persists, please provide the full error message (text version, if possible) and any relevant logs to better diagnose the problem.

Thank you for your patience, and let's get this sorted out! 🛠️

**Comment by UltralyticsAssistant** [comment]
@VarunNelakanti great to hear that you've verified the checkpoint file and the dataset integrity.

To resume training from an earlier checkpoint:

1. Locate the checkpoint files. These should be named with the epoch number or similar identifier.
2. Select an earlier checkpoint file than the most recent one.
3. Use the training command you usually would, but specify the path to the earlier checkpoint file as the resume argument.

This process will tell the training script to pick up from the epoch that the earlier checkpoint corresponds to, rather than the latest one.

If you’re having trouble with the specific command syntax, please consult the Ultralytics HUB Docs on the Training section, which should provide the necessary guidance for resuming from a given checkpoint.

Should you encounter any further issues after trying to resume from an earlier checkpoint, please provide the exact error text (not as a screenshot) here, and I’ll be happy to assist you in troubleshooting the matter. Keep up the good work! 🌟
