### ISSUE TITLE
Timeout - No response from server

### ISSUE THREAD

**Issue by PHIKHONAMTHEMBU** [ultralytics/hub#494]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hi, I am uploading a dataset into the hub, it has been running for atleast 10 hrs, and I get timeout, not response from the server error. 

It uploaded 100%, loading seems to be the problem.
![server timeout](https://github.com/ultralytics/hub/assets/16671146/e6062eb3-d9f2-46a2-8de4-57e28f8c973c)

### Environment

Ultralytics HUB Version
v0.1.31
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
1920 x 973
Server Timestamp
1702353466

**Comment by UltralyticsAssistant** [comment]
@PHIKHONAMTHEMBU hello!

I'm sorry to hear you're experiencing an upload issue with a dataset to the HUB. A timeout after uploading 100% suggests there might be some issue during the final stages of processing on the server side. Here are a few steps you might consider:

1. Please make sure the dataset doesn't exceed our current size limits and it adheres to the required format specified in our documentation.
2. If everything is in order and you are still facing the same issue, try uploading the dataset again after refreshing the page or restarting your browser.
3. If the problem persists, it might be related to a temporary server issue. In this case, waiting for a while before attempting another upload could resolve the issue.
4. Check your internet connection to ensure a stable upload process.

Should none of these steps resolve the issue, please reply to this with the exact time (including time zone) when the issue occurred, and we'd be glad to investigate further. You're also welcome to visit the Ultralytics HUB Docs for more detailed instructions on uploading datasets and troubleshooting.

Thank you for using the Ultralytics HUB, and we appreciate your patience as we work to resolve your issue. 😊

**Comment by PHIKHONAMTHEMBU** [comment]
I have checked the above, and I don't see any obvious issues relating to points above. 

I have attached some sample labels and yaml format just for confirmation.
![image](https://github.com/ultralytics/hub/assets/16671146/a6de0012-1672-4cd6-aa32-e46ae7bf61aa)
![image](https://github.com/ultralytics/hub/assets/16671146/0d3187ce-c291-43a6-919d-011df1787099)

**Comment by UltralyticsAssistant** [comment]
Thank you for the update, @PHIKHONAMTHEMBU.

Since you've confirmed that the dataset format and size are within our guidelines, and the issue persists, it might be best to look into this matter more deeply on our end.

Unfortunately, I'm unable to view the images you've attached directly in this format. However, you can ensure that your labels and YAML files are correctly formatted by cross-referencing them with the examples provided in our documentation.

If you're confident that the files are correct, I would recommend the following:

- Document the exact steps you're taking to upload the dataset, including any specific settings or options you're choosing.
- Note the time and date of another upload attempt, and if it fails, provide this information in your response.

This information will be crucial for our team to replicate the issue and identify a solution. We're committed to improving your experience with the Ultralytics HUB, and your detailed feedback is invaluable in this process.

Thank you for your cooperation, and we look forward to resolving this issue for you soon! 😊

**Comment by PHIKHONAMTHEMBU** [comment]
Hi, 

thank you for responding. I am confident on the above steps mentioned. can you share the py script that pre validates .zip file before uploading into the hub.

it use to be available in some of the discussion topics :)

**Comment by UltralyticsAssistant** [comment]
Hello again, @PHIKHONAMTHEMBU!

I'm glad to hear you're confident in the steps you've taken. While I understand you're looking for a Python script to pre-validate your .zip file, I'm unable to provide code examples directly. However, I can guide you on what the script generally does:

The pre-validation script typically checks for:
- Correct directory structure within the .zip file.
- Properly formatted label files that match the expected naming conventions and data formats.
- Consistency between the image files and their corresponding label files.
- Adherence to any size limitations or file type restrictions.

To create such a script, you would write Python code that:
- Opens and reads the contents of the .zip file.
- Validates the structure and contents against the criteria mentioned above.

For the exact implementation details, you can refer to the documentation or past discussions where similar scripts have been shared. If you have further questions or need additional assistance, feel free to reach out.

Thank you for your patience and for working with us to ensure a smooth experience with the Ultralytics HUB! 😊

**Comment by PHIKHONAMTHEMBU** [comment]
is there a maximum dataset size limit to the amount of data that can be uploaded even though there is enough storage available? my dataset is about 40GB with 72GB storage availability. 

If I upload, for example, a sample dataset with just a few images <1GB it gets uploaded successfully. uploading the full set gives No response from the server error

**Comment by UltralyticsAssistant** [comment]
Yes, @PHIKHONAMTHEMBU, there is indeed a maximum dataset size limit for uploads to the Ultralytics HUB, even if you have sufficient storage available. The limit is in place to ensure optimal performance and manage server load effectively.

While the exact size limit can vary and may be subject to change, a 40GB dataset could potentially exceed the current maximum allowed size for a single upload, which might explain why you're encountering the "No response from the server" error for the full set but not for a smaller sample dataset.

To address this, you could try splitting your 40GB dataset into smaller chunks that are below the maximum size limit and upload them separately. This approach can help avoid timeouts and server errors due to large file sizes.

If you need further clarification on the current size limits or assistance with managing your dataset, please refer to our documentation or reach out for support. We're here to help ensure your data is uploaded successfully to the Ultralytics HUB. 😊

**Comment by PHIKHONAMTHEMBU** [comment]
ok, yeah that makes sense, I have just uploaded 10GB and It was successfully uploaded. I will look at splitting the dataset.  It would also be nice to add a footnote to indicate max upload size, it creates a false impression when you look at available storage and assume that there is no limit to how much one can upload.

**Comment by UltralyticsAssistant** [comment]
I'm glad to hear that uploading a smaller portion of your dataset was successful, @PHIKHONAMTHEMBU! Splitting the dataset is indeed a good strategy to work around the upload size limitations.

Your feedback regarding the maximum upload size is very valuable. I agree that having a clear indication of the maximum upload size on the platform would help set the right expectations and prevent similar issues. I'll pass this suggestion along to our team for consideration in future updates to the HUB.

Thank you for bringing this to our attention, and we appreciate your understanding. If you have any more questions or need further assistance, please don't hesitate to reach out. We're here to support you! 😊
