### ISSUE TITLE
Can not download model

### ISSUE THREAD

**Issue by IsraPiyayo** [ultralytics/hub#495]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

![Screenshot 2023-12-13 230606](https://github.com/ultralytics/hub/assets/117136840/1473d291-0beb-4882-baf5-ac84373dee1e)
I want to download model but progress not update

**Comment by UltralyticsAssistant** [comment]
@IsraPiyayo hello! I'm sorry to hear you're experiencing issues with downloading a model from the Ultralytics HUB. Let's try to troubleshoot this together!

First, ensure that you have a stable internet connection, as intermittent connectivity can sometimes cause downloads to stall. If your connection is stable but the problem persists, it could be a temporary issue with the server or your browser might be causing a problem. You could try:

- Refreshing the page to see if the download progress resumes.
- Using a different web browser or clearing your browser's cache and cookies before attempting the download again.
- If you're behind a firewall or using a VPN, consider temporarily disabling them to see if it affects the download process.

For more detailed guidance on model downloading issues, our documentation at the Ultralytics HUB Docs could provide you with additional troubleshooting steps.

If the issue doesn't resolve, we'd be happy to assist you further! Don't hesitate to provide us with any error messages you see or additional details about the steps you've taken thus far. Your patience is appreciated as we work to sort this out. 🛠️

**Comment by kalenmike** [comment]
@IsraPiyayo Thank you for raising this bug. Can you provide us your model id so that we can look into this further? You can find it in the URL on the model page.

**Comment by IsraPiyayo** [comment]
I'm not sure if I understand it correctly. I use YOLOv8x

**Comment by UltralyticsAssistant** [comment]
Hello @IsraPiyayo, thanks for the additional details!

If you're attempting to download YOLOv8x and the progress isn't updating, the first step is to make sure that the issue isn't on the client-side. Since you've already checked your internet connection and browser, consider giving it some time as large models can take a while to download depending on the server load and your connection speed.

If after some time the issue remains unresolved, one option is to restart the download process. If you consistently face download issues specifically with YOLOv8x, please let us know. This information will help us investigate whether there might be a larger underlying issue with that specific model.

We understand these situations can be frustrating and appreciate your patience. If you continue to face difficulties, you can reply to this issue with any error messages or a description of any changes in the situation, and we'll provide further assistance. You're also welcome to check our documentation for any updates on known issues and resolutions. 🌟
