### ISSUE TITLE
Upload not working dataset

### ISSUE THREAD

**Issue by akghost96** [ultralytics/hub#50]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

error: Dataset Error : data.yaml/images/train not found, data.yaml/labels/train not found, data.yaml/images/valid not found, data.yaml/labels/valid not found
i tried to make the data file exactly like in the coco6.yalm
data.yalm :

path: 
train: images/train
val: images/valid

nc: 4
names: ['black_measles', 'black_root', 'blight', 'healthy']

one document annotation:
1 0.60703125 0.45 0.03671875 0.034375
1 0.5375 0.490625 0.034375 0.03125
1 0.6875 0.534375 0.04375 0.04765625
1 0.63984375 0.55703125 0.03515625 0.03203125
1 0.4390625 0.559375 0.02890625 0.025
1 0.671875 0.64140625 0.03203125 0.02734375
1 0.6140625 0.6421875 0.03203125 0.03125
1 0.82109375 0.71640625 0.053125 0.05
1 0.44375 0.16640625 0.0421875 0.0359375
1 0.453125 0.275 0.03203125 0.0328125
1 0.43984375 0.359375 0.04296875 0.03515625

I tried to make the zip file with the same name with the yalm file still not working and getting the same error

**Comment by kalenmike** [comment]
@akghost96 Thank you reaching out. If you are seeing an error like that it is because the YAML file cannot be found, most likley you are seeing the error because you have set the extension to be `.yalm` when it should be `.yaml`.

You can also confirm that your YAML is correctly configured. The train and val keys you see in the YAML are indicating the location of your images. With the config file you are showing above your folder structure should be like this:

`YOUR_DATASET_NAME
--images
----train
------ ...all your training images
----valid
------ ...all your validation images
--labels
----train
------ ...all your training labels
----valid
------ ...all your validation labels
YOUR_DATASET_NAME.yaml`

I hope that this helps you to upload your custom dataset. If you have any other issues please let us know.
