### ISSUE TITLE
How should I set the model output parameters to be [125200, n] instead of [1, n8400]

### ISSUE THREAD

**Issue by alinikou** [ultralytics/hub#508]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I use C # language to use the trained model. When I export the trained yolov5nu model to onnx format, I find that its output is in [1, n, 8400] format instead of the [125200, n] format I used before. This prevents me from using the previous code to call the current model. What do I need to do to make the exported model compatible with the previous code

**Comment by UltralyticsAssistant** [comment]
@alinikou hello! To modify the output tensor shape of your YOLOv5 model, you'd have to adjust the model's architecture or post-processing steps before or after the ONNX export. The changes depend on how your model's exported structure was set up initially.

If you originally had a model outputting in the [125200, n] format, it implies that you might have had a different stride or a modified version of the architecture. For the exact transformation to the desired format, you would need to ensure that the model's last layer or the post-processing code reshapes or slices the output accordingly to fit your current pipeline.

To make the model output compatible with your existing code without altering the exported ONNX model, you might consider adapting your C# code to reshape the tensor from [1, n, 8400] to [125200, n] directly in your application. You will need to handle the data to match your expected dimensions, ensuring integrity and correct mapping of the original content.

Since coding is beyond my current support guidelines, I would recommend reviewing the documentation or reaching out to the community for specific code snippets or further instructions. You can refer to the Ultralytics HUB Docs for more information on the export process and model customization.

Do let us know if you have other questions, and best of luck with your model adjustments! 😊
