### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ultralytics/yolov5/hubconf.py'

### ISSUE THREAD

**Issue by DJMike2** [ultralytics/hub#519]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I seem to not have a hubconf.py. There are similar bug reports but all solutions have not worked. If I remove the 'source='local'' then I get 'Detect' object has no attribute 'grid'. I am not sure what to do anymore. I have up to date all modules from torch and ultralytics.

### Minimal Reproducible Example

**from ultralytics import YOLO
torch.hub.load('ultralytics/yolov5/','custom',path='C:/Users/shkro/source/repos/Trainer/Trainer/Cars/train23/weights/best.pt',source='local')**

**Comment by kalenmike** [comment]
@DJMike2 It looks like you are combining the ultralytics package (YOLOv8) and the YOLOv5 code. Is this intentional? Did you train your model using ultralytics or yolov5?

If your intention is to use ultralytics you can run prediction like this:

```python
from ultralytics import YOLO

# Load model
model = YOLO('path/to/weights.pt')

# Run inference on an image
results = model('path/to/image.jpg')  # list of 1 Results object
```

If your intention is to use yolov5 you can run prediction like this:

```python
import torch

# Load model
model = torch.hub.load("ultralytics/yolov5", "custom", path="path/to/weights.pt")  # or yolov5n - yolov5x6, custom

# Run inference on an image
results = model("path/to/image.jpg")
```

Does this provide a solution?
