### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by markatlarge** [ultralytics/hub#527]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

While training my model in the hub on that last epoch I got this error:

FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/best.pt

If I look in the hub under the model you see the blue circle spinning even though I got the error message.

**Comment by UltralyticsAssistant** [comment]
@markatlarge hello! I'm sorry to hear you're encountering a `FileNotFoundError` during your model training on the Ultralytics HUB. It seems like the training process is trying to access the 'best.pt' file, which should contain the weights of the best-performing model, but it's not found in the expected directory.

This could be due to a few reasons, such as the file not being saved correctly, or an issue with the path configuration. Here's what you can do:

1. **Check the Training Configuration**: Ensure that the output directory is set correctly and that the process has the necessary permissions to write to that directory.
2. **Inspect the Output Directory**: Manually check the specified directory to see if the 'best.pt' file exists. It's possible that the file might be in a different location.
3. **Review the Training Logs**: Look through the training logs for any indications of why the file wasn't saved or if there were any errors during the saving process.
4. **Training Interruption**: If the training was interrupted or didn't complete successfully, the 'best.pt' file might not have been created.

If the issue persists, please provide additional details about your training setup and any steps you've already taken to troubleshoot the problem. This will help us assist you more effectively.

For further guidance, you can refer to the Ultralytics HUB Docs, which might have additional troubleshooting steps or relevant information.

We appreciate your patience and are here to help you get back on track with your training! 🚀

**Comment by markatlarge** [comment]
@UltralyticsAssistant I'm using the ultralytics hub (hub.ultralytics), so from what I know we dont have access to that information.  

I re-ran the model again and of course its on colabs so it stops, then when I try to restart the training I got this error,  

Ultralytics HUB: New authentication successful ✅
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-ffc849acdb3d>](https://localhost:8080/#) in <cell line: 3>()
      1 hub.login('ce0c9365d1d98f8f928166db59f301dbcae09f190b')
      2 
----> 3 model = YOLO('https://hub.ultralytics.com/models/rezEQgTO2hKhsV6gQDku')
      4 results = model.train()

5 frames
[/usr/local/lib/python3.10/dist-packages/hub_sdk/modules/models.py](https://localhost:8080/#) in get_weights_url(self, weight)
    204         """
    205         if weight == "last":
--> 206             return self.data("resume")
    207 
    208         return self.data.get("weights")

TypeError: 'dict' object is not callable

**Comment by markatlarge** [comment]
@UltralyticsAssistant 

I was using Ultralytics HUB, 

This is the code i executed with my information in colabs
hub.login('API_KEY')  # use your API key

model = YOLO('https://hub.ultralytics.com/MODEL_ID')  # use your model URL
results = model.train()  # train model

its looking at the "https://hub.ultralytics.com/MODEL_ID" to find the last.pt and it can not.  

Is there away in the UI i can check or some other way in the colabs note book.   Here is the error message when I execute the code: 
Ultralytics HUB: New authentication successful ✅
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-62e54e917c02>](https://localhost:8080/#) in <cell line: 3>()
      1 hub.login('ce0c9365d1d98f8f928166db59f301dbcae09f190b')
      2 
----> 3 model = YOLO('https://hub.ultralytics.com/models/pf4EK86gcHR9864jfOPr')
      4 
      5 

5 frames
[/usr/local/lib/python3.10/dist-packages/hub_sdk/modules/models.py](https://localhost:8080/#) in get_weights_url(self, weight)
    204         """
    205         if weight == "last":
--> 206             return self.data("resume")
    207 
    208         return self.data.get("weights")

TypeError: 'dict' object is not callable

**Comment by markatlarge** [comment]
@UltralyticsAssistant - In order to train the model I go into the hub, copy the code and go to the colabs note book link in the hub:  

In the note book I run this to install Ultralytics 

%pip install ultralytics  # install
from ultralytics import YOLO, checks, hub
checks()  # checks

The version is indicated aa: Ultralytics YOLOv8.1.0.

Ill crate this as a issue

**Comment by UltralyticsAssistant** [comment]
Thank you for the update, @markatlarge. It's good to hear that you're using the latest version of the Ultralytics YOLOv8.1.0. Since you're still encountering the issue, creating an issue on the Ultralytics HUB GitHub repository is indeed the right course of action. The development team will be able to take a closer look at the problem and work on a resolution.

When you create the issue, please include all the relevant details such as the error message, the steps you've taken, and the version of the SDK you're using. This information will be very helpful for the developers to understand and replicate the issue.

We appreciate your cooperation and patience as we work to resolve this. Your contributions help improve the experience for the entire YOLO community. Thank you for your support! 🌟

**Comment by kalenmike** [comment]
@markatlarge I don't have enough information to confirm what your initial error was, but the second error relating to resume is due to a bug we introduced in the last hub-sdk. This has been patched:

https://github.com/ultralytics/hub/issues/529
