### ISSUE TITLE
The Trained model is not appearing in the mobile application 

### ISSUE THREAD

**Issue by athulkannan2000** [ultralytics/hub#530]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

The Trained model is not appearing in the mobile application, Like the privet and the unlisted models are showing empty

**Comment by UltralyticsAssistant** [comment]
@athulkannan2000 hello! Thank you for reaching out. If your trained models are not appearing in the mobile application, it could be due to a few reasons such as synchronization issues or privacy settings. Here are a few steps you can take to troubleshoot the problem:

1. Ensure that you are logged into the same account on both the HUB and the mobile application.
2. Check if the models are set to 'private' or 'unlisted' and confirm that you have the necessary permissions to view them.
3. Try refreshing the model list in the mobile app or logging out and back in to force a sync.
4. Make sure that the mobile app is updated to the latest version.

If the issue persists after these steps, please refer to the Ultralytics HUB Docs for further guidance or consider submitting a detailed bug report with the environment information and any relevant screenshots.

We appreciate your contribution to the YOLO community and the Ultralytics team is here to help! 😊

**Comment by saulacunha** [comment]
Tengo en mismo problema, he hecho todo lo sugerido y aún así no aparece mis modelos.
![17052527020832337925351660862706](https://github.com/ultralytics/hub/assets/18223198/a0e9e089-1b44-4359-a358-61dcd2f1843e)
Incluso, me aparece esto al querer exportarlo.

**Comment by UltralyticsAssistant** [comment]
Hola @saulacunha, lamento escuchar que sigues teniendo problemas. Si has seguido los pasos sugeridos y aún así los modelos no aparecen y además te encuentras con un error al intentar exportarlos, parece que podríamos estar frente a un problema más específico que requiere una revisión detallada.

Te recomendaría que documentes el problema con la mayor cantidad de detalles posibles, incluyendo el mensaje de error completo y cualquier otra información relevante sobre el comportamiento que estás experimentando. Luego, por favor, envía esta información a través de un nuevo reporte de problema en el repositorio de GitHub para que el equipo pueda investigar y asistirte de manera adecuada.

Asegúrate de incluir detalles sobre el dispositivo y la versión de la aplicación móvil que estás utilizando, así como cualquier paso específico que puedas haber seguido que resulte en el error. Esto ayudará al equipo a reproducir y entender mejor el problema.

Agradecemos tu paciencia y estamos comprometidos a ayudarte a resolver este inconveniente. ¡Gracias por ser parte de nuestra comunidad y por tu colaboración! 😊

**Comment by kalenmike** [comment]
@saulacunha Did the weights ever get repaired? Or are you still facing the same issue? Can you share the model id with me so I can look into this please.

@athulkannan2000 Thanks for raising this, we are looking into a solution as this is a confirmed bug on the current version of the app.
