### ISSUE TITLE
Models not appearing in app

### ISSUE THREAD

**Issue by kwayne-08** [ultralytics/hub#546]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

I have two trained models in my hub, but they do not show in my android app.

**Comment by UltralyticsAssistant** [comment]
@kwayne-08 hello! Thank you for reaching out with your issue. 😊

If your trained models are not appearing in the Android app, it could be due to a few reasons:

1. **Sync Issue**: There might be a synchronization issue between the HUB and the app. Please ensure you are logged into the same account on both platforms.

2. **App Update**: Make sure that your app is updated to the latest version, as older versions might not support all features.

3. **Visibility Settings**: Check if the models are set to be visible within the app. There might be settings in the HUB that control whether a model appears in the app or not.

4. **Network Connection**: Ensure that your device has a stable internet connection to sync with the HUB.

If you've checked these potential issues and the problem persists, please refer to the Ultralytics HUB Docs for troubleshooting steps or consider submitting a detailed bug report with steps to reproduce the issue.

We appreciate your contribution to the YOLO community and are here to help you resolve this! 🌟

**Comment by Shyamcme** [comment]
Hi 
I am facing the same issue after the latest app update on android mobile.

My trained model which was previously visible is no longer seen, also none of my unlisted/private projects are visible, i have logged onto the same account as i can see the datasets, the issue is with the models only

it looks like a bug and needs resolution, happy to assist with my ID if reqd

Thx in advance

**Comment by UltralyticsAssistant** [comment]
Hello @Shyamcme,

Thank you for the additional information and for offering to assist with your ID. Since the issue started after the latest app update, it's possible that there might be a bug related to the update.

Here's what you can do next:

1. **Clear Cache**: Try clearing the app's cache on your Android device. Sometimes, this can resolve issues that arise after updates.

2. **Re-login**: Log out of your account in the app and log back in. This can help refresh your account's connection to the HUB.

3. **Report the Bug**: Since this seems to be related to the latest update, it would be helpful to report this as a bug. Please provide your user ID and any relevant details about the issue (without sharing sensitive information publicly) in the bug report. This will help the development team to investigate and address the issue more effectively.

We apologize for the inconvenience and appreciate your patience as we work to resolve this. Your assistance is invaluable in helping us improve the app for everyone in the YOLO community! 🛠️

**Comment by Shyamcme** [comment]
Hello, Thanks for the update

I have tried all the steps as suggested by you above including clearning cache, re-login etc

My User ID : mtechthesis11@gmail.com

I am attaching the screen shot from my android app, wherein you can see that non of my private/unlisted projects are being displayed. However my datasets are being shown under private & unlisted category.

I am also attaching the screen capture Ultralytics Hub platform logged in from my laptop which displays the models and projects

Do let me know , if  I can assist in any other way, Regards
![WhatsApp Image 2024-01-28 at 23 08 43](https://github.com/ultralytics/hub/assets/144660698/d6e0b030-eb2c-4ba9-9ac2-691ab134649c)
![WhatsApp Image 2024-01-28 at 23 08 44 (1)](https://github.com/ultralytics/hub/assets/144660698/249c76d9-7e47-44d9-b13b-95f035920e57)
![WhatsApp Image 2024-01-28 at 23 08 44](https://github.com/ultralytics/hub/assets/144660698/edf59e37-28ff-4a75-8e7e-81e76e55f88e)
![WhatsApp Image 2024-01-28 at 23 08 45](https://github.com/ultralytics/hub/assets/144660698/47c655ba-d952-45b9-b17d-2e55164a791e)

Below are screenshots from the web browser 

<img width="960" alt="Screenshot 2024-01-28 231253" src="https://github.com/ultralytics/hub/assets/144660698/45a57ec4-8a39-42da-8013-9236971d21b5">
<img width="958" alt="Screenshot 2024-01-28 231236" src="https://github.com/ultralytics/hub/assets/144660698/8a37b569-423b-4fa7-ae01-3247a2affd55">

**Comment by pderrenger** [comment]
Hello @Shyamcme,

Thanks for following up with those details and providing screenshots. Based on what you've described and shown, it does seem like there's an inconsistency between what you see in the app versus the HUB on the web. Since you've already tried the basic troubleshooting steps without success, it seems we're indeed dealing with a bug that needs attention from our development team.

Given the information and screenshots you've shared, I'll forward this to our development team for further investigation. Your User ID and the details you've provided will be crucial in diagnosing the issue.

In the meantime, if there's any other way you think you could assist or any other detail you remember that might be relevant, please feel free to share. Your cooperation is much appreciated as we seek to resolve this. Your patience and support are invaluable to us and the broader YOLO community! 🌟
