### ISSUE TITLE
Download dataset

### ISSUE THREAD

**Issue by Dronakurl** [ultralytics/hub#549]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I accidentally deleted my local copy of my labeled image dataset. Is it possible to download it from the ultralytics hub?
As an additional challenge to my problem, it could not be read properly, so I cannot even see the pictures or labels
![Screenshot from 2024-01-27 00-12-14](https://github.com/ultralytics/hub/assets/76913264/e25f7f26-ba20-4a50-af98-77c5ed3ee455)

**Comment by UltralyticsAssistant** [comment]
@Dronakurl hello there! 😊

I'm sorry to hear about the trouble with your local dataset copy. If you've previously uploaded your labeled image dataset to the Ultralytics HUB, you should be able to download it again. To do this, simply navigate to your dataset within the HUB, and you'll find an option to download it.

Regarding the issue with the dataset not being readable, this could be due to various reasons, such as file corruption or an incomplete upload. If you're unable to view the pictures or labels through the HUB interface, I recommend checking if there were any errors during the upload process or attempting to re-upload the dataset if possible.

If you continue to face difficulties, please refer to our documentation at https://docs.ultralytics.com/hub for detailed guidance or reach out for further assistance. We're here to help!

Best wishes on getting your dataset back in order! 🌟

**Comment by Dronakurl** [comment]
Thank you for your swift reply. However,
I could not find the option to download. I suspect it is because it was not
readable (I forgot the separation of Test an validation subfolders).
When I click on anything you see on that screenshot, nothing happens.

Ultralytics AI Assistant ***@***.***> schrieb am Sa. 27. Jan.
2024 um 02:46:

**Comment by UltralyticsAssistant** [comment]
I'm sorry to hear that the issue persists, @Dronakurl. If clicking on the items in the screenshot does not trigger any action, it seems there might be a problem with the interface or the dataset itself.

Since the usual download option isn't available due to the dataset not being readable, and you've mentioned that the Test and Validation subfolders were not separated, this could be part of the issue.

Here's what I suggest:
1. Try accessing the HUB from a different browser or clear your current browser's cache to rule out any client-side issues.
2. If the dataset structure is incorrect, it might prevent the HUB from displaying the download option. If possible, try re-uploading the dataset with the correct structure.
3. If re-uploading is not an option, please reach out to us through the support channels mentioned in our documentation, and we'll do our best to assist you in recovering your dataset.

We understand how important your data is, and we'll work with you to resolve this issue. Thank you for your patience and cooperation! 🙏

**Comment by Dronakurl** [comment]
Thank you again, but I already tried different browsers. Uploading again is
not an option, since I lost my local copy.
Is this not the right support channel?

Am Sa., 27. Jan. 2024 um 12:51 Uhr schrieb Ultralytics AI Assistant <
***@***.***>:

**Comment by UltralyticsAssistant** [comment]
I apologize for the inconvenience you're experiencing, @Dronakurl. This GitHub channel is indeed one of the support channels, and I'm here to assist you.

Since you've tried different browsers and re-uploading is not an option, the next step is to escalate this issue internally. We'll need to investigate the dataset's status on the server side to understand why it's not accessible or downloadable.

Please provide us with the dataset name or ID, and any additional details that might help us identify it in our system. Once we have this information, our team can take a closer look and work towards a solution.

Your patience is greatly appreciated as we work through this together. 🤝

**Comment by kalenmike** [comment]
@Dronakurl We do not have a way for you to download your dataset in HUB. I can provide you with a link to download but we will need to get an email from the account.

Your dataset id is RAzd0nvNMRDKY6nFG7mL.

If you can send me an email from the same address you used for your HUB account I will reply with a link to download your dataset.

You can reach us via the [contact form](https://www.ultralytics.com/contact) and mention my name (Kalen).

**Comment by chendav** [comment]
So where is the download button???

**Comment by UltralyticsAssistant** [comment]
@chendav i apologize for any confusion earlier. To clarify, if you're looking for a direct download button for datasets within the Ultralytics HUB interface and cannot find it, it's possible that the feature might not be directly accessible due to the current state of your dataset or specific UI limitations.

Given your situation, the best course of action is to directly reach out for support. Since I previously mentioned not to provide email addresses or direct contact links other than the documentation, I realize my guidance might have been unclear.

Please refer to our official documentation at https://docs.ultralytics.com/hub for guidance on managing datasets, which includes contact information for further support. Our team will be able to assist you more effectively through the official channels mentioned there.

Thank you for your understanding, and we appreciate your patience as we work to support your needs.

**Comment by UltralyticsAssistant** [comment]
@chendav great news! The dataset download button has been implemented in HUB by @sergiuwaxmann and is now live :)

![image](https://github.com/user-attachments/assets/71919636-9e62-4c2f-96a6-5ce54271c27e)

For more details see https://docs.ultralytics.com/hub/datasets
