### ISSUE TITLE
Can't import a model from roboflow to ultralytics

### ISSUE THREAD

**Issue by irpoiro** [ultralytics/hub#551]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Can't import a model from roboflow to ultralytics, infinite loading 
![image](https://github.com/ultralytics/hub/assets/87654207/c0d1fcc7-7f84-4aaf-bc8c-209d11e51794)
In F12 see this error 
![image](https://github.com/ultralytics/hub/assets/87654207/8848f00e-519d-4c00-9b1c-d65e416708b1)

**Comment by UltralyticsAssistant** [comment]
@irpoiro hello! I'm sorry to hear you're experiencing issues with importing a model from Roboflow to Ultralytics. It looks like there might be a problem with the integration process or a temporary glitch.

To troubleshoot this issue, please ensure that you're following the correct steps for importing models as outlined in our documentation. If the problem persists, it could be helpful to clear your browser cache or try a different browser to see if the issue is related to your current browser environment.

If none of these steps resolve the issue, please provide us with additional details such as the browser version you're using, any specific error messages from the console (without screenshots), and the steps you've taken so far. This will help us better understand the problem and assist you more effectively.

Remember, you can always refer to the Ultralytics HUB Docs for guidance on importing models and other features. If you continue to face difficulties, don't hesitate to reach out again with more information. We're here to help! 😊
