### ISSUE TITLE
Final Weights Not Uploading for YOLOv8x

### ISSUE THREAD

**Issue by typeacyclist** [ultralytics/hub#554]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/detect/train3
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/100      8.05G     0.7111     0.3119     0.9955          9        640: 100%|██████████| 210/210 [02:28<00:00,  1.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 11/11 [00:06<00:00,  1.60it/s]
                   all        182        183      0.915      0.915      0.951      0.488

1 epochs completed in 0.051 hours.
Optimizer stripped from runs/detect/train3/weights/last.pt, 136.7MB
Ultralytics HUB: Syncing final model...
Ultralytics HUB: WARNING ⚠️ Model upload issue. Missing model runs/detect/train3/weights/best.pt.
Ultralytics HUB: Done ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/dFqLS4d8bbEE7WVfUEde 🚀

### Environment

Ultralytics HUB Version
v0.1.33
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
1705 x 1269
Server Timestamp
1706735948

**Comment by UltralyticsAssistant** [comment]
@typeacyclist hello! It looks like you've encountered an issue where the `best.pt` file is missing after training completion. This file should be generated if the model achieves a new best performance on the validation dataset during training. If it's missing, it could be due to a few reasons:

1. The model might not have improved upon its metrics, and therefore, a `best.pt` was never saved. This can happen if the model's performance does not surpass the previous best or if there's an issue with the validation data.
2. There could be a path or saving issue where the file is not being written to the expected directory.
3. It's also possible that there's a bug in the code that's preventing the `best.pt` file from being saved.

To troubleshoot, please ensure that your validation dataset is correctly set up and that the model is indeed improving during training. Also, check the specified paths for saving weights to confirm they are correct. If the problem persists, you might want to review the training logs for any additional clues.

For further guidance, you can refer to the Ultralytics HUB Docs, which might provide additional insights into the expected behavior and configuration for model training and saving.

If you continue to face issues, please provide more details about your training setup, and we'll be happy to assist you further. 😊

**Comment by typeacyclist** [comment]
Retrying but now Colab will not initiate
/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py<https://localhost:8080/> in _run_command(cmd, clear_streamed_output)
    166         locale_encoding = locale.getpreferredencoding()
    167
--> 168         # If current encoding is not UTF-8, set the locale to UTF-8
    169         if locale_encoding != _ENCODING:
    170             locale.setlocale(locale.LC_ALL, 'C.UTF-8')

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968


***@***.***

-Matt
Matt Gabrielson
馬特 葛柏森
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Website https://trendzact.com/
My Availability Calendar Book Time with ***@***.***/bookings/>

**Comment by UltralyticsAssistant** [comment]
@typeacyclist hello Matt,

It seems you're encountering a locale issue on Google Colab, which is unrelated to the Ultralytics HUB. The error message indicates that Colab requires a UTF-8 locale, but it's encountering an ANSI_X3.4-1968 encoding.

This is typically a system-level issue on the environment you're running Colab in. To resolve this, you may need to set the locale to UTF-8 manually. You can usually do this by running a command in the Colab notebook to set the locale environment variables to UTF-8.

If you're still having trouble after trying to set the locale, I would recommend seeking assistance on forums specific to Google Colab or looking through their documentation for guidance on setting up the correct locale.

For any further issues related to the Ultralytics HUB, feel free to reach out, and we'll be happy to help. 😊

**Comment by typeacyclist** [comment]
Thanks for the response.
 I was able to start and keep restarting until the process finished with Colab © but the Ultralytics Hubs shows 100% (A) yet still Optimizing weights for hours (B).
Can you help release it?

***@***.***

-Matt
Matt Gabrielson
馬特 葛柏森
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Website https://trendzact.com/
My Availability Calendar Book Time with ***@***.***/bookings/>

**Comment by UltralyticsAssistant** [comment]
@typeacyclist hello Matt,

I'm glad to hear you were able to get your process running on Colab. Regarding the issue with the Ultralytics HUB showing the model as still optimizing weights, this could be a display or synchronization issue.

Please try the following steps to potentially resolve the issue:

1. Refresh the HUB page to see if the status updates correctly.
2. Check if there are any error messages or logs in the HUB that could give more information about the delay.
3. Ensure that your internet connection is stable, as a drop in connectivity might cause synchronization issues.

If the problem persists and the HUB still indicates that it's optimizing weights after a considerable amount of time, it might be a backend issue that needs to be looked into by our team.

In this case, please provide the model ID or any relevant details that could help us identify the model in question, and we'll investigate the matter further.

Thank you for your patience, and we'll do our best to assist you in resolving this issue. 😊

**Comment by typeacyclist** [comment]
I have reconnected to Colab 5 x but there isn’t any CSV to process.
Can you have someone take a look?
https://hub.ultralytics.com/models/MktuA2hgqRMkXjwFz4Oh

-Matt
Matt Gabrielson
馬特 葛柏森
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Website https://trendzact.com/
My Availability Calendar Book Time with ***@***.***/bookings/>

**Comment by UltralyticsAssistant** [comment]
@typeacyclist hello Matt,

Thank you for providing the model ID. I understand that you're experiencing issues with the CSV not being processed on Colab and the model status on the Ultralytics HUB.

I will forward this information to our technical team to take a closer look at the model with the provided ID: MktuA2hgqRMkXjwFz4Oh. They will investigate the current status and any potential issues with the processing of the CSV.

Please allow some time for the team to diagnose and address the problem. We appreciate your patience and will update you as soon as we have more information or if further details are required from your end.

Thank you for bringing this to our attention, and we're on it! 😊

**Comment by kalenmike** [comment]
@typeacyclist It looks like you are having an issue uploading the final weights. This is a known issue for the X model that we are still working to resolve.

I am curious are you seeing failure messages for your checkpoints during training as well?

**Comment by typeacyclist** [comment]
I deleted it and ran an s without issue.

-Matt
Matt Gabrielson
馬特 葛柏森
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Website https://trendzact.com/
My Availability Calendar Book Time with ***@***.***/bookings/>

**Comment by UltralyticsAssistant** [comment]
@typeacyclist Matt,

I'm glad to hear that you were able to successfully run an 's' model without issue. It seems the problem was specific to the 'x' model, which is consistent with the known issue we're working on.

If you encounter any further issues or have additional questions, please don't hesitate to reach out. Your feedback is valuable in helping us improve the Ultralytics HUB.

Thank you for your understanding and for being a part of the YOLO community! 😊
