### ISSUE TITLE
Tried to run training on the cloud for 24 hrs, stuck on disconnected. After deleting the broken model, lost my top-up funds

### ISSUE THREAD

**Issue by kev0051** [ultralytics/hub#588]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

![Screenshot 2024-02-25 at 8 22 37 PM](https://github.com/ultralytics/hub/assets/126007369/cc9fbee2-7748-4d1d-8110-f097adf48334)
![Screenshot 2024-02-25 at 8 23 44 PM](https://github.com/ultralytics/hub/assets/126007369/59ed4208-4a58-415c-b9ae-29acdb292da6)

This is what it looked like for me when it started and then after it disconnected. I deleted previous instances training on epochs (also stuck on disconnected) and it never took money from my top-up. Afterwards I tried running it for 24 hrs and it took the money. I didn't realize this and deleted the training instance because it was stuck on disconnected and I ended up losing $17.76

### Minimal Reproducible Example

Models -> Train Models -> Started training yolov8n on my dataset for 24 hours

**Comment by kalenmike** [comment]
@kev0051 Apologies for this. I will look into what happened and ensure that your account is refunded.

**Comment by kalenmike** [comment]
@kev0051 I have refunded the funds to your account wallet balance. The issue we have at the moment is we do not have enough storage space assigned in Cloud Training to handle your large dataset. We will get this fixed and let you know when you are good to try again.

Apologies for this and thank you for your patience and understanding.

**Comment by OliseNS** [comment]
I am going through this same problem right now. It disconnects, and when I restart it, it is stuck on loading. This makes me not progress with my task, as I have to wake up and keep restarting

![Image](https://github.com/user-attachments/assets/87d69619-2f01-4d94-afe6-6433ea5a751b)

**Comment by pderrenger** [comment]
Thank you for reporting this issue. We're actively working to improve Cloud Training reliability and resolve these disconnection problems. A few suggestions while we investigate:

1. **Dataset Size Check**: Ensure your dataset meets Cloud Training requirements (currently optimized for datasets under 10GB). Larger datasets may require special provisioning - our team is working to expand storage capacity  
2. **Alternative Training**: For critical tasks, you might consider temporarily using [Google Colab integration](https://docs.ultralytics.com/integrations/google-colab/) as a fallback  
3. **Session Monitoring**: If a session disconnects, check the Billing tab first before deleting - funds are only deducted for completed epochs/training time  

Our engineers are implementing enhanced session recovery mechanisms and improved resource allocation that should resolve these stability issues in upcoming updates. 🔄

If you experienced fund deductions due to failed sessions, please:  
1. Reply with your account email  
2. Include training session timestamps  
We'll ensure proper refunds while we work on permanent fixes. 

Thank you for your patience as we enhance Cloud Training reliability! 🚀
