### ISSUE TITLE
option to change training mid training from collab to private agent, resume and change setup from gpu to cpu 

### ISSUE THREAD

**Issue by Omer1004** [ultralytics/hub#595]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

option to change training mid training from collab to private agent, resume and change setup from gpu to cpu 

### Use case

add option in the hub to change from gpu training to cpu training on private agent so that I can resume the training on another device and flags like device='mps' and resume=True doesnt work when working with the hub

**Comment by UltralyticsAssistant** [comment]
@Omer1004 hello! Thank you for bringing up this feature request. 🌟

Currently, the ability to switch training environments (from Colab to a private agent) or hardware (from GPU to CPU) mid-training and resuming seamlessly is not directly supported through the Ultralytics HUB interface. This involves complex state management and hardware compatibility considerations, especially when transitioning between different types of devices and environments.

However, we understand the flexibility this feature could offer and the potential benefits for users who need to adapt their training workflows due to various constraints. We'll take this suggestion into our planning discussions for future updates. Your input is invaluable in helping us improve.

For now, to manage training across different environments or hardware, you might need to manually stop your training, download your latest checkpoint, and restart the training on the new setup by specifying the checkpoint. Please refer to our documentation at https://docs.ultralytics.com/hub for guidance on managing training sessions and checkpoints.

We appreciate your contribution to the discussion and your interest in making the Ultralytics HUB more versatile! Keep the suggestions coming. 🚀
