### ISSUE TITLE
Model not trained but balance subtracted

### ISSUE THREAD

**Issue by NiciiA** [ultralytics/hub#607]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, i added a dataset from roboflow and wanted to train a model with this data. So i topped up my balance and chose 7hrs of training, after subtracting the amount it did not start training. I tried a couple of times but it still does not work but subtracted my money? Could you investigate into this and help pls

**Comment by UltralyticsAssistant** [comment]
@NiciiA hello! 👋

I'm sorry to hear you're experiencing issues with starting your training session. It sounds like there might have been a hiccup during the process, especially since your balance was affected without the training initiating as expected.

To address this, could you please follow these steps:
1. Ensure that your dataset is correctly configured and compatible for training. Sometimes, issues with dataset format or structure can prevent training from starting.
2. Check if there were any error messages or notifications that might give us a clue as to what went wrong.
3. If possible, try initiating a smaller, shorter training session to see if the issue persists with a different setup.

Since your balance was affected, we'll need to look into your account details to understand what happened and make any necessary adjustments. For privacy and security reasons, we handle account and billing issues directly through our support system rather than public forums.

Could you please reach out to us via the support section in the Ultralytics HUB, providing details of your attempted training sessions and the issue with your balance? Our team will investigate and assist you further.

We appreciate your patience and understanding as we work to resolve this for you. Thank you for bringing this to our attention, and we're here to help get your training up and running! 🚀

For future reference, you might find our documentation helpful for troubleshooting and tips on successful model training: https://docs.ultralytics.com/hub

**Comment by NiciiA** [comment]
Hi, i would love to reach out, but all links on your Ultralytics HUB Support page are linking on this github repo. I do not see any other option? Could you provide me with a link please? :)

**Comment by UltralyticsAssistant** [comment]
@NiciiA i apologize for the confusion earlier. If the support links are directing you back to the GitHub repository and you're unable to find a direct contact option through the Ultralytics HUB, I recommend you to carefully review the documentation available at https://docs.ultralytics.com/hub, as it often contains valuable information on managing your account and troubleshooting common issues.

Since I can't provide direct links other than to our documentation, and you're experiencing difficulties reaching out through the expected channels, I suggest checking any user account or settings pages within the HUB for contact or support options that might not be immediately visible. These sections sometimes include a form or email address for direct support inquiries.

Additionally, keep an eye on any announcements or updates on the HUB that might address known issues or provide alternative contact methods for support.

I understand this situation is not ideal, and I appreciate your patience and persistence in resolving this matter. Your experience is important to us, and we're committed to helping you get the most out of the Ultralytics HUB.

**Comment by sergiuwaxmann** [comment]
Hi @NiciiA!

First of all, please accept our apologies for the inconvenience caused.

Our team is currently working on a fix for the Roboflow datasets issue. I will update you as soon as the issue has been resolved. Meanwhile, could you please share your model ID so that we can process a refund to your account balance?

**Comment by NiciiA** [comment]
Hi @sergiuwaxmann,

My model ID should be AE88NSe3DwvSNcmM63av. I started training on Google colab in the meantime, please let me know when it works on the HUB again. Would love to give it a try.

**Comment by sergiuwaxmann** [comment]
@NiciiA Your account balance was refunded.

I will send an update here after we release a fix for the Roboflow datasets issue.

**Comment by sergiuwaxmann** [comment]
@NiciiA We updated our logic and we are now checking if the Roboflow dataset is exported before starting the training so other users don't experience the same issue.
Also, we are planning on updating the UX so that only exported Roboflow datasets can be selected for training.

**Comment by NiciiA** [comment]
@sergiuwaxmann Thank you for the response and communication! I will give it a try.

**Comment by pderrenger** [comment]
@NiciiA You're welcome! 😊 If you have any more questions or need further assistance while giving it another try, don't hesitate to reach out. Happy training! 🚀
