### ISSUE TITLE
error on preview

### ISSUE THREAD

**Issue by dougkote** [ultralytics/hub#608]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

<img width="714" alt="Screenshot 2024-03-10 at 5 37 37 AM" src="https://github.com/ultralytics/hub/assets/64851719/0ca9651a-8dfc-4d48-b2f4-7ab15bb5c72b">

**Comment by UltralyticsAssistant** [comment]
@dougkote hello! 👋

Thank you for reporting this issue. It seems like there's a problem with the project preview functionality. To help us diagnose and address this issue more efficiently, could you please provide a bit more detail?

1. **Description of the Error**: A brief description of what happens when the error occurs.
2. **Steps to Reproduce**: Any specific steps that lead to the error, if you haven't already done so.
3. **Expected vs. Actual Behavior**: What you expected to happen versus what actually happened.

In the meantime, you might find some helpful information in our documentation: https://docs.ultralytics.com/hub. 

We appreciate your contribution to making the Ultralytics HUB better! 🚀

**Comment by sergiuwaxmann** [comment]
Hi @dougkote!
Thank you for bringing this issue to our attention.
We were able to replicate this issue and are working on a fix now.

To streamline our efforts and keep the discussion centralized, we are going to manage and track the progress of this issue here https://github.com/ultralytics/hub/issues/609 going forward.
