### ISSUE TITLE
On demand balance being drained far faster than actual usage

### ISSUE THREAD

**Issue by TheEndurance** [ultralytics/hub#610]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

It seems like on demand balance is being drained faster than what is actually being used.  I started with $20 as my balance.  I ran some training in a google colab overnight and it completed about 30 epochs before disconnecting.  I check this morning, and it says that training took place for about 3 hours, at $0.74/per hour.  I check my on demand balance and it was down to $10.24.

The actual usage is 3 hours * $0.74 = $2.22, but my balance was drained for more than 4 times that amount.

### Environment

Google Colab:

Ultralytics YOLOv8.1.27 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
(2 CPUs, 12.7 GB RAM, 26.4/78.2 GB disk)

### Additional

[billing.pdf](https://github.com/ultralytics/hub/files/14589974/billing.pdf)
![image](https://github.com/ultralytics/hub/assets/26070869/bc43250c-0d09-4974-a65e-c9bd333aed3b)

**Comment by TheEndurance** [comment]
Model ID: 60Goorihl8zdxg8Fk4vc

I tried training with ultralytics cloud several times, and it just gives the message waiting for cloud instance to start, then after about 15 minutes that message goes away and it goes back to the original menu.  No error messages or anything appear to indicate any issue.

I used the dataset validation tool to make sure there is no issue there and it reported no problems.

That's when I tried google collab option instead and at least that was working.

**Comment by UltralyticsAssistant** [comment]
Thank you for providing the model ID, @TheEndurance!

It sounds like there are two separate issues here:

1. **Unexpected Balance Deduction**: Based on your description, it seems there might have been attempts to start cloud training sessions that didn't fully initiate but could have inadvertently affected your balance. I'll look into the logs for model ID `60Goorihl8zdxg8Fk4vc` to understand what happened during the cloud instance provisioning attempts. This will help us identify if there were any glitches or errors that led to balance deductions without actual usage.

2. **Issues with Cloud Instance Provisioning**: The problem you're encountering with the cloud instance not starting and reverting back to the original menu without any error messages is certainly not the expected behavior. This could be due to a temporary shortage of cloud resources or an issue within our provisioning system. I'll investigate this specific model's provisioning attempts to pinpoint the cause and ensure it gets addressed.

For Google Colab, it's important to note that it operates independently of Ultralytics Cloud Training, with its own pricing and resource management. It's great that you were able to use it as an alternative, but I understand that it's not the solution you were initially aiming for.

I'll start by looking into both issues immediately and will update you as soon as I have more information. Your patience and understanding are greatly appreciated as we work to resolve these matters. 🛠️

**Comment by sergiuwaxmann** [comment]
@TheEndurance
Yesterday we experienced an issue with our training instances due to failed driver installation. This caused requested Ultralytics Cloud Training requests to be put in a queue. After we resolved this issue, one of your Ultralytics Cloud Training requests was initialized twice for the same model. We have refunded this duplicate charge.

Once again, we apologies for the inconvenience caused.
