### ISSUE TITLE
Hub freezes up with "Preparing your cloud instance..."

### ISSUE THREAD

**Issue by oliverlibaw** [ultralytics/hub#633]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I'm unable to use Ultralytics Cloud to train a YOLO model on a custom dataset using the Hub. 

The Hub gets stuck on "Preparing your cloud instance... hang tight!" After about 10 minutes, it simply refreshes to the previous screen. There's no error message. 

I have a Pro account with a few $ in training credits. 
![Screenshot 2024-04-10 at 1 16 01 PM](https://github.com/ultralytics/hub/assets/92615450/bdb55f17-487e-4010-ac21-f0dcc4d913c1)

### Environment

Ultralytics HUB Version
v0.1.39
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Operating System
MacIntel
Browser Window Size
789 x 846
Server Timestamp
1712779695

### Minimal Reproducible Example

My model training URL is https://hub.ultralytics.com/models/Ck8CJvrXbVNklZtRA0uA

My dataset is : https://hub.ultralytics.com/integrations/roboflow/datasets/oliver-libaw%2Fcats-squirrels

Thanks for any help you can provide!

**Comment by pderrenger** [comment]
Hello! 😊 Thanks for reaching out with detailed information about the issue you're encountering. It really helps us get to the bottom of things more quickly.

It looks like you're facing a hang-up during the cloud instance preparation phase when trying to train a YOLO model on a custom dataset. This might be due to a temporary service disruption or an issue with the allocation of cloud resources for your account.

Here are a few steps you can try to resolve the issue:
1. **Refresh the browser** - Sometimes a simple refresh can help re-initiate the connection.
2. **Clear your browser cache** - This can help resolve any stored conflicts that might be causing the hang-up.
3. **Try a different browser** - to rule out any browser-specific issues.
4. **Wait and retry** - If Ultralytics HUB is experiencing high traffic or undergoing maintenance, it might be worth waiting a bit before attempting to start the training again.

If after trying these steps, you're still facing the same issue, it would be good to report this directly via the HUB so our technical team can take a closer look. Make sure to include the information you've provided here, as it's very useful for debugging.

We're here to make sure you have the best experience with the Ultralytics HUB, so don't hesitate to reach out if you have further issues or questions. For more detailed troubleshooting steps, please visit our Docs at https://docs.ultralytics.com/hub.

Thanks for being part of the Ultralytics community!

**Comment by sergiuwaxmann** [comment]
Hello @oliverlibaw!
Thank you for reaching out and bringing this to our attention.
The message you're encountering is indeed expected behavior as part of the initialization process for your Cloud Training instance. This process involves spinning up a dedicated instance equipped with GPU resources, which can sometimes take a while depending on the current demand and availability of GPU resources.

**Comment by sergiuwaxmann** [comment]
@oliverlibaw 

We just discovered that we have an issue when training Roboflow datasets using our Cloud Training (see #645). Our team is investigating this issue, and we'll update you as soon as we implement a solution.

We appreciate your patience and understanding.

**Comment by sergiuwaxmann** [comment]
Hello @oliverlibaw!
We just released a new version that fixes the issue you had.

**Comment by oliverlibaw** [comment]
awesome! Thanks for the update @sergiuwaxmann

**Comment by pderrenger** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask. Happy training! 😊
