### ISSUE TITLE
上传含有中文的数据集有乱码

### ISSUE THREAD

**Issue by linkuiyuan** [ultralytics/hub#640]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

上传含有中文的数据集有乱码

### Minimal Reproducible Example

![微信截图_20240415104059](https://github.com/ultralytics/hub/assets/157896575/460034a1-0110-4486-bfc1-ed8ff1b27d84)

**Comment by yogendrasinghx** [comment]
@linkuiyuan  Thank you for bringing this to our attention. We're currently investigating the root cause of the issue regarding the garbled characters in datasets containing Chinese text. Our team is actively working on resolving this matter, and we'll update you as soon as we confirm the problem and implement a solution.

We appreciate your patience and understanding.

**Comment by sergiuwaxmann** [comment]
@linkuiyuan
Can you share more information with us?
Did you format your dataset correctly following our [documentation](https://docs.ultralytics.com/hub/datasets/#upload-dataset)? FYI, you can validate your dataset:
```python
from ultralytics.hub import check_dataset
check_dataset('path/to/coco8.zip')
```
Maybe you can try re-uploading your dataset?
