### ISSUE TITLE
Training hub not working

### ISSUE THREAD

**Issue by ilanb** [ultralytics/hub#645]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Tried multiple time to start training but nothing happen and after some minutes page reloaded and start training button appear again

Preparing your cloud instance... Hold tight!
This could take up to 10 minutes. Thank you for waiting!

After X time message removed and nothing happen, just start training button appear again

**Comment by pderrenger** [comment]
Hello! Sorry to hear you're encountering issues with the Training component on the Ultralytics HUB. It sounds like there could be a hiccup with initializing the cloud instance for your training session. A few quick things to try:

1. **Refresh your browser**: Sometimes a simple page refresh can resolve the issue.
2. **Clear Browser Cache**: Stale cache data may sometimes interfere with web applications. Clearing it might help.
3. **Try a different browser**: This helps determine if the issue is browser-specific.

If the problem persists, there might be a temporary issue on our side or a specific issue with your account or setup. Please provide any relevant details (while avoiding sensitive information) such as the browser used, and a screenshot of any error messages (if any) as an update here. This will help us dig deeper into the issue.

Thank you for your patience, and apologies for the inconvenience! We appreciate your support for the YOLO community and the Ultralytics team. 🌟

For more guidelines and troubleshooting tips, you might find our documentation helpful: https://docs.ultralytics.com/hub.

**Comment by ilanb** [comment]
I already tried Safari and chrome (last version) on OSX, is always same problem, the training don’t start. I already charged 200$ and 20$.
For a paid service is not really good… and no support just GitHub… please give some advice or just check my account ?

Best,

**Comment by sergiuwaxmann** [comment]
Hello @ilanb!
Thank you for reaching out and bringing this to our attention.
The message you're encountering is indeed expected behavior as part of the initialization process for your Cloud Training instance. This process involves spinning up a dedicated instance equipped with GPU resources, which can sometimes take a while depending on the current demand and availability of GPU resources.

Maybe you can try starting the process again and share the model ID with us so that we can analyze the logs of your Cloud Training instance? You can find the model ID in the URL of the model page.

**Comment by ilanb** [comment]
Thanks for quick reply, I can understand for the GPU resources but I tried 2 days at day and night…

Model: https://hub.ultralytics.com/models/QrgKsFLsZDLZ9dsW20wi


I use personal dataset from ROBOFLOW too

Best,

**Comment by sergiuwaxmann** [comment]
@ilanb Maybe the Roboflow dataset wasn't exported from Roboflow properly (issue on their end). If you try starting the Cloud Training again, I can monitor your instance and see if there are any errors.

**Comment by ilanb** [comment]
Just started again now 😉Envoyé de mon iPhoneLe 17 avr. 2024 à 12:32, Sergiu Waxmann ***@***.***> a écrit :﻿
@ilanb Maybe the Roboflow dataset wasn't exported from Roboflow properly (issue on their end). If you try starting the Cloud Training again, I can monitor your instance and see if there are any errors.

**Comment by sergiuwaxmann** [comment]
@ilanb I just checked the logs on your instance and indeed, we have an issue in our logic when we download the Roboflow dataset. Please accept our apologies for the inconvenience caused. Our team is investigating this issue, and we'll update you as soon as we implement a solution.
We appreciate your patience and understanding.

**Comment by sergiuwaxmann** [comment]
Hello @ilanb!
We just released a new version that fixes the issue you had.
Once again, apologies for the inconvenience caused.
