### ISSUE TITLE
Unable to login using Apple Sign In

### ISSUE THREAD

**Issue by ongaroandrea** [ultralytics/hub#676]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

Hi everyone,
I'm trying to log in my ultralytics account but it gives me this error every time I try.
"Unable to login with apple.com, please try again in a few minutes."

I tried a different browser but same error. I'm able to use my account on my iPhone, but not from my computer.  

### Environment

- MacBook Pro 14" 2021
- Safari Versione 17.4.1 (19618.1.15.11.14)
- Chrome v. 119.0.6045.159 (arm64)

### Minimal Reproducible Example

1. Go to https://hub.ultralytics.com/signin
2. Click on apple logo 
3. Log in with apple credentials 
4. Error

**Comment by yogendrasinghx** [comment]
Hi @ongaroandrea,

Thank you for bringing this to our attention and for providing detailed information. I can confirm that this is indeed a bug, and we have been able to reproduce it on our end. I have transferred this issue to our development team to resolve it as quickly as possible.

Please wait for an update; I will let you know as soon as the bug has been resolved. We appreciate your patience and are working diligently to fix this issue so that you can log in seamlessly from your computer.

Thank you for your patience.

**Comment by yogendrasinghx** [comment]
Hi @ongaroandrea,

I'm pleased to inform you that the issue you reported has been resolved by our development team. You can now sign in using your Apple ID without any further problems.

Please try logging in and let us know if everything is working as expected on your end. We appreciate your patience and are here to assist you if you encounter any further issues.

Thank you for bringing this to our attention, and for your understanding throughout the resolution process.

**Comment by ongaroandrea** [comment]
Hi @yogendrasinghx,
thank you too. Now it works again. 

Have a nice day!

**Comment by pderrenger** [comment]
Hi @ongaroandrea,

Great to hear it's working again! If you have any more questions in the future, feel free to reach out. Have a wonderful day! 😊
