### ISSUE TITLE
Fail to train model through HUB

### ISSUE THREAD

**Issue by ch-ho00** [ultralytics/hub#677]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

![image](https://github.com/ultralytics/hub/assets/36185920/943ed36e-4fb8-4948-8a6d-deb5ea774643)

All of my training seems to fail every time I try to train a model through the hub. I am unable to see any training result either because it is "disconnected". 

### Environment

- Computer : Macbook Pro 14 
- Browser : Chrome 

### Minimal Reproducible Example

1. Login to hub 
2. Upload dataset
3. Train model in models tab

### Additional

 I have paid for subscription and also credits to train the model. Can I request for a refund or some compensation in any way?

**Comment by pderrenger** [comment]
Hello! 😊

Thanks for reaching out and sorry to hear about the issue you're experiencing. It sounds frustrating, but I’m here to help!

Given the symptoms you're describing, the problem might relate to browser compatibility, connectivity issues, or potential bugs on the dashboard. Here are a couple of steps you could try:
- **Clear your browser cache** and cookies, and then attempt to log in and initiate training again.
- **Try a different browser** or a private/incognito window to rule out extension-related issues.
- Ensure that your internet connection is stable, as intermittent connections can cause disruptions during training.

Since you've also inquired about a refund, I’d recommend reaching out directly via the support contact provided within the HUB's billing or help section, as I'm unable to process such requests directly from here.

For a more detailed walkthrough, you can visit the [Ultralytics HUB Docs](https://docs.ultralytics.com/hub).

If the issues persist, please provide any specific error messages you are seeing, and we'll take a closer look!

**Comment by sergiuwaxmann** [comment]
@ch-ho00 Hi there!
Did you train the 3 models from the SS you shared using Ultralytics Cloud Training? Can you share the model IDs?

**Comment by ch-ho00** [comment]
@pderrenger  I am not sure where you want me to reach out regarding the refund. I don't see a contact or any other channel both in the billing or help section to reach customer service. There are only links and redirects to this repository.

**Comment by sergiuwaxmann** [comment]
@ch-ho00 I just analyzed the models you shared.

The first two models (`FuW9tX6Gop7VgMrv6jWI` and `6K2o0pXeL8kGROeZM40y`) didn't start training and you saw the "Disconnected" status as most likely the 15 minutes timeout was reached. The initialization process involves spinning up a dedicated instance equipped with GPU resources, which can sometimes take a while depending on the current demand and availability of GPU resources - if no resources are available within 15 minutes, we show the "Disconnected" status and allow the user to try again (by clicking the "Start Training" button). No account balance was deducted for these models.

The last model (`dcj3x57bo1JoZMjyD3SG`) trained for 14 epochs (checkpoint saved for epoch 14) and was either stopped by the user, the account balance wasn't enough for the next epoch, or an error occurred during the training session, causing the training session to stop. The account balance deducted from your account is linked to the 14 epochs trained.

Looks like you tried training the models a while ago as you used Ultralytics Cloud version 0.1.7. I suggest you start training again as we updated our Ultralytics Cloud to version 0.1.12 that fixes many issues (I don't think the fixes we added are related to your training but you should use the new version if possible).

CC @yogendrasinghx
