### ISSUE TITLE
Problem with uploading Pose dataset

### ISSUE THREAD

**Issue by sctcorp01** [ultralytics/hub#681]
### Search before asking

- [x] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I conducted the dataset validation check post-upload. 
and I've got answer "Checks completed correctly ✅. Upload this dataset to https://hub.ultralytics.com/datasets/."
But, When I upload dataset to HUB, I get "Invalid, Unable to process the dataset."

What are the possible reasons for this error? and what should I have to do?

### Additional

Here's my Environment Details.
- Ultralytics HUB Version: v0.1.42
- Client User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Operating System: Win32
- Browser Window Size: 1920 x 919
- Server Timestamp: 1715330909

And here's my Data Details.
- The type of dataset : Pose (I exported dataset from CVAT as yolo 1.1 and separate files with 'images' and 'labels')
- The size of dataset: 99.0 MB (314 train images/labels and 52 val images/labels)

**Comment by sergiuwaxmann** [comment]
Hello @sctcorp01!

I'm sorry to hear about the issue you're encountering.

If you hover over the error on the dataset card, it should reveal the exact problem. Based on the latest logs, I think this is the problem your dataset has: `'kpt_shape' in data.yaml missing or incorrect. Should be a list with [number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)], i.e. 'kpt_shape: [17, 3]'`.

Normally, running the following command should highlight this issue:
```python
from ultralytics.hub import check_dataset

check_dataset('path/to/dataset.zip')
```
However, since your checks completed without flagging this error, I have escalated this issue to our development team to investigate and resolve as soon as possible. Thank you for bringing this to our attention, and we'll keep you updated on the progress.

**Comment by sergiuwaxmann** [comment]
@sctcorp01 New version of `ultralytics` released (8.2.14)! The new version updates the `check_dataset` method -  the `path` and `task` parameters are no longer optional ([see docs](https://docs.ultralytics.com/reference/hub/__init__/#ultralytics.hub.check_dataset)), forcing users to specify the dataset task (and by doing so, possibly preventing bad uploads).

**Comment by pderrenger** [comment]
Hello again @sctcorp01! 😊

I'm glad to hear that adding the 'kpt_shape' and 'flip_idx' worked out for your dataset!

Regarding your question, **yes**, currently, for uploading datasets on Ultralytics HUB, every label file needs to be in `.txt` format. While exporting from CVAT, you should convert your `.xml` files into `.txt` files for each image. The HUB specifically supports the YOLO format for labels, which requires this `.txt` format.

Converting `.xml` to `.txt` may seem daunting, but you might use scripting to automate the conversion process depending on the structure of your XML files. 

Thanks for reaching out, and don't hesitate to ask if you have more questions. Good luck with your project! 🌟

**Comment by sctcorp01** [comment]
Hola!
Thanks to your helps, I have uploaded datasets and start model training finally.
Problems still occur occasionally, but I'm making progress.

During training, I have some "Traceback" logs which doesn't make my training stop. 
After it occurred, training is restarted continuously soon.

I add some log.txt here.
[training_log.txt](https://github.com/ultralytics/hub/files/15385201/training_log.txt)

I would like to know "why this 'Traceback' logs occured" and "doesn't it any matter to my training?"
Always Thanks for your detailed answer.

**Comment by pderrenger** [comment]
Hola!

Great to hear that you've made progress with your model training! 🚀

Regarding the "Traceback" logs you're encountering, these are often due to temporary issues such as network interruptions or resource constraints on the server. Since your training automatically restarts and continues, it suggests that the system is designed to recover from such minor issues without impacting the overall training process.

However, it's always good to keep an eye on these logs. If the errors become frequent or start affecting your model's performance, it might be worth investigating further. You can share more detailed logs or error messages if the issue persists or escalates.

Keep up the good work, and don't hesitate to reach out if you have more questions!

**Comment by sctcorp01** [comment]
Thanks a lot!!!
I will keep checking. :)

**Comment by pderrenger** [comment]
@sctcorp01 you're welcome! 😊 If anything else comes up, feel free to reach out. Happy training!
