### ISSUE TITLE
 Ultralytics Pro member doesn't work dataset

### ISSUE THREAD

**Issue by Geniuspond** [ultralytics/hub#716]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Even though I am an Ultralytics Pro member and have funds in my balance, your system has not been processing the dataset for about four days. I am urgently awaiting a proposed solution.

### Additional

![Ekran görüntüsü 2024-06-08 221109](https://github.com/ultralytics/hub/assets/172143517/0d10f06e-6771-4f6d-b52c-343955663eb9)

**Comment by sergiuwaxmann** [comment]
@Geniuspond Hello!

I just checked our system and everything works fine.

If you are having issues uploading your dataset:
1. Follow the steps in [our documentation](https://docs.ultralytics.com/hub/datasets#upload-dataset).
1.2. Validate your dataset locally before uploading it to [Ultralytics HUB](https://hub.ultralytics.com).
```python
from ultralytics.hub import check_dataset
check_dataset("path/to/dataset.zip", task="detect")
```
2. Make sure you have a stable internet connection.

In the image you attached, I can see that Ultralytics Cloud is not available because you are training another model. Unfortunately, at the moment, you can only train one model at a time using Ultralytics Cloud.
