### ISSUE TITLE
Resolution Option, Does it need to be square 1920*1920? Can I do 1920*1080?

### ISSUE THREAD

**Issue by felixho789** [ultralytics/hub#727]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Resolution Option, Does it need to be square 1920*1920? Can I do 1920*1080?
As the ultralytics HUB doesn't seems like allowing me to put 1920*1080 in the image size

**Comment by pderrenger** [comment]
@felixho789 hello!

Thank you for reaching out with your question. The Ultralytics HUB does not strictly require a square resolution like 1920x1920 for your images. You can indeed use a resolution of 1920x1080. However, there are a few considerations to keep in mind:

1. **Aspect Ratio**: Ensure that the aspect ratio of your images is consistent with your dataset to avoid any distortion during training or inference.

2. **Image Size Configuration**: If the HUB interface is not allowing you to set a non-square resolution, it might be due to a specific configuration or a potential bug. Please make sure you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk`. You can update your packages using the following commands:
   ```bash
   pip install --upgrade torch ultralytics hub-sdk
   ```

3. **Minimum Reproducible Example**: If you continue to face issues, could you please provide a minimum reproducible code example? This will help us understand the problem better and offer a more precise solution. You can refer to our documentation on how to create a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

We appreciate your cooperation and look forward to assisting you further. If you have any more questions or need additional help, feel free to ask!
