### ISSUE TITLE
Ultralitics HUB can retrieve Roboflow dataset to train

### ISSUE THREAD

**Issue by santiago-unxdigital** [ultralytics/hub#734]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets, Training

### Bug

When i try to train a model into hub and the dataset come from roboflow, the value of data parameter into the yml file created from hub is NULL.

This is a recurrent error, no matters what dataset im using, or model, no matter what device im using to train (colab, my laptop, etc)

The error is de Null into the data parameter into the yml file created by hub.
![Uploading Screenshot from 2024-06-19 11-19-17.png…]()

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Hello!
This issue occurs when the Roboflow dataset isn't exported.
When you create your model in [Ultralytics HUB](https://hub.ultralytics.com), we request Roboflow to export the dataset, and I noticed that sometimes the export takes a while.

**Comment by santiago-unxdigital** [comment]
yes, i know that. but the issue is into hub. the data value is NULL. roboflow already provide the url to get the dataset, as you can see in the attached image
![Uploading Screenshot from 2024-06-19 12-15-58.png…]()

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital I can't see the attached image.

**Comment by santiago-unxdigital** [comment]
![Screenshot from 2024-06-19 12-15-58](https://github.com/ultralytics/hub/assets/45884843/0f431674-7b63-4e41-a9e8-a23007a62ebd)

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Yes, the screenshot in from the Roboflow platform. Unfortunately, they have a different export for the [Ultralytics HUB](https://hub.ultralytics.com) integration which has the issue I explained above.
Maybe you can share your model ID with me so that I can check if the export for the [Ultralytics HUB](https://hub.ultralytics.com) integration is ready or not? You can find the model ID in the model's URL.

**Comment by santiago-unxdigital** [comment]
'https://hub.ultralytics.com/models/JoPCqWmE0vxbNABuM5pz'

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Just checked, and indeed the issue is that the export for the [Ultralytics HUB](https://hub.ultralytics.com) integration is not ready.
You could force Roboflow to re-trigger the export by creating a new model in [Ultralytics HUB](https://hub.ultralytics.com) using the same dataset.

**Comment by santiago-unxdigital** [comment]
i did! a lot of times! there any way to enter maually the data value? as a custom value of data parameter?

the zip from roboflow is https://app.roboflow.com/ds/j6OrgaYiZp?key=TjjUqndDOT

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Unfortunately, there is no way to do this now. Additionally, this is not part of our feature roadmap, but I have noted this feature request, and we might work on it in the future.
I suggest reporting this issue to Roboflow, as there is nothing wrong on our end related to Roboflow training.

**Comment by santiago-unxdigital** [comment]
i disagree with you. the issue is in hub, the NULL value for data parameter is your problem. this is a bug for hub

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital As stated above, I have noted your feature request: allowing users to specify/customize the data parameter when training. Once again, the `data` value is `null` because the Roboflow export for the [Ultralytics HUB](https://hub.ultralytics.com) integration is not successful or slow.
I will prioritize highlighting in the UI the Roboflow dataset export status for the next [Ultralytics HUB](https://hub.ultralytics.com) release.

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Funny enough, I can see the export is ready now. Please try to start training again.

**Comment by santiago-unxdigital** [comment]
same thing , data=NULL
![Screenshot from 2024-06-19 13-08-56](https://github.com/ultralytics/hub/assets/45884843/0ca268cb-4180-43f4-98b1-df86e4ab68f4)

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Can you try with this model: https://hub.ultralytics.com/models/JoPCqWmE0vxbNABuM5pz? This is the one I monitored and noticed that was updated by Roboflow.

**Comment by santiago-unxdigital** [comment]
4 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/hub/session.py](https://localhost:8080/#) in load_model(self, model_id)
     75         self.model = self.client.model(model_id)
     76         if not self.model.data:  # then model does not exist
---> 77             raise ValueError(emojis("❌ The specified HUB model does not exist"))  # TODO: improve error handling
     78 
     79         self.model_url = f"{HUB_WEB_ROOT}/models/{self.model.id}"

ValueError: ❌ The specified HUB model does not exist

**Comment by sergiuwaxmann** [comment]
@santiago-unxdigital Did you take the training code snippet from the model page (https://hub.ultralytics.com/models/JoPCqWmE0vxbNABuM5pz)? Asking as the error you shared indicates that the model ID in the training code is invalid.
