### ISSUE TITLE
This account is currently being deleted?

### ISSUE THREAD

**Issue by DGKang234** [ultralytics/hub#740]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! An error occurs when logging into my google account: 

"This account is currently being deleted." 

Please restore my account: kdg4206@gmail.com

### Additional

*N/A

**Comment by pderrenger** [comment]
@DGKang234 hello!

Thank you for reaching out and bringing this to our attention. It sounds like you're encountering an issue with logging into your Google account on the Ultralytics HUB. Unfortunately, if the error message states that "This account is currently being deleted," it indicates that the issue is on Google's end rather than with the Ultralytics HUB platform.

Here are a few steps you can take to resolve this issue:

1. **Verify with Google**: Please check with Google support to confirm the status of your account and see if it can be restored. You can visit the [Google Account Help Center](https://support.google.com/accounts/) for assistance.

2. **Try a Different Account**: If the issue persists and you need immediate access to the Ultralytics HUB, you might consider using a different Google account or creating a new one temporarily.

3. **Stay Updated**: Ensure that you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk` packages. This can help avoid any compatibility issues.

If you have any further questions or need additional assistance, feel free to ask. We're here to help!

**Comment by sergiuwaxmann** [comment]
@DGKang234 Your account was reactivated.

**Comment by DGKang234** [comment]
@sergiuwaxmann  I am sorry the system still tells me that my account is deleted... How can I prevent this?

**Comment by sergiuwaxmann** [comment]
@DGKang234 Your account was reactivated.

**Comment by DGKang234** [comment]
<img width="1501" alt="image" src="https://github.com/ultralytics/hub/assets/59916992/865cef5f-5c43-4a80-aa14-08512849744a">

It still doesn't work... is there way that I can solve this issue from my side?

**Comment by sergiuwaxmann** [comment]
@DGKang234 Can you confirm the email you are using to log in?

**Comment by DGKang234** [comment]
@sergiuwaxmann it's **kdg4206@gmail.com**

**Comment by sergiuwaxmann** [comment]
@DGKang234 It looks like the account was deleted again yesterday. Your account was reactivated (3rd time).

**Comment by DGKang234** [comment]
@sergiuwaxmann I don't understand why it keep deleting my acc. Is there anything that I can do to prevent this?

Thank you for your time.

**Comment by sergiuwaxmann** [comment]
@DGKang234 After I reactivated your account, maybe you clicked by mistake on the "Delete All Data" button?

**Comment by DGKang234** [comment]
@sergiuwaxmann  I'm sorry. I attempt to log in today again and it's.... deleted again!
I have not clicked any button...

**Comment by DGKang234** [comment]
@sergiuwaxmann This time I might change the account once I back up the data...

**Comment by sergiuwaxmann** [comment]
@DGKang234 Done, apologies for the inconvenience.

**Comment by DGKang234** [comment]
@sergiuwaxmann oh god.. I don't know why it keep deleting me.... Could you please reactivate me? I will backup again and delete the account and make the account again?

**Comment by sergiuwaxmann** [comment]
@DGKang234 Your account was reactivated.
