### ISSUE TITLE
Can't export tensorflow lite

### ISSUE THREAD

**Issue by togro** [ultralytics/hub#751]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

Can't export to Tensorflow Lite, alway fail with retry/failed

<img width="228" alt="image" src="https://github.com/ultralytics/hub/assets/7252575/0fe9f909-24d8-45b6-a03c-50923c96696f">

**Comment by pderrenger** [comment]
@togro hello,

Thank you for reaching out and reporting this issue. To assist you better, could you please provide a minimal reproducible example? This will help us understand the context and pinpoint the problem more effectively. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of all relevant packages, as updates often contain important bug fixes and improvements.

Looking forward to your response so we can help resolve this issue promptly! 😊

**Comment by sergiuwaxmann** [comment]
@togro Hello!
I verified and everything works correctly. Do you still have this issue?
![SCR-20240701-fgp](https://github.com/ultralytics/hub/assets/47978446/941e1e28-3c0f-409e-b231-4e1be75a97ec)

**Comment by togro** [comment]
It is not working .... I tried to many times ...

**Comment by pderrenger** [comment]
Hello @togro,

Thank you for reaching out and for your patience. I'm sorry to hear that you're experiencing issues with exporting to TensorFlow Lite.

To help us diagnose the problem more effectively, could you please provide a minimal reproducible example? This will allow us to better understand the context and specifics of the issue you're encountering. You can find guidance on creating a minimal reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of all relevant packages. Sometimes, issues can be resolved by simply updating to the most recent release.

Looking forward to your response so we can assist you further!

**Comment by togro** [comment]
Dear Paula,I don't understand your email, I am using your platform to generate these models.If you want to see an example you can look at the model: Potholes01-yolov8m, which in the other exports shows that it works.The model URL is: https://hub.ultralytics.com/models/yGfk3twdeVSxv7OV34AcMy email for your pro service is ***@***.*** and I usually log in through github.I cannot generate a minimum reproducible example of something that does not work well on your platform and does not send any message that helps, except "Failed, Retry?"What I do ? It doesn't occur to me, retraining is not viable because I can end up in the same situation.What is expected from me, since I have your pro service, is that you review my account and see what the problem is, as you can see in the images of the previous emails, it exports well to EdgeTpu and ONNX, but it fails in TensorFlow Lite.Best regards
        
        
          On jul. 1 2024, at 6:34 pm, Paula Derrenger ***@***.***> wrote:
          
        
        
          
Hello @togro,
Thank you for reaching out and for your patience. I'm sorry to hear that you're experiencing issues with exporting to TensorFlow Lite.
To help us diagnose the problem more effectively, could you please provide a minimal reproducible example? This will allow us to better understand the context and specifics of the issue you're encountering. You can find guidance on creating a minimal reproducible example here: Minimum Reproducible Example.
Additionally, please ensure that you are using the latest versions of all relevant packages. Sometimes, issues can be resolved by simply updating to the most recent release.
Looking forward to your response so we can assist you further!

**Comment by pderrenger** [comment]
Hello @togro,

Thank you for providing additional details and for your patience. I understand the frustration when things don't work as expected, especially when other export formats are functioning correctly.

Given that the issue seems specific to TensorFlow Lite and other formats like EdgeTPU and ONNX are working fine, it might be an isolated problem. Here are a few steps we can take to troubleshoot this further:

1. **Verify Latest Versions**: Ensure that you are using the latest version of the Ultralytics HUB and all relevant packages. Sometimes, updates include fixes for issues like these.

2. **Model Review**: Since you mentioned the model URL (https://hub.ultralytics.com/models/yGfk3twdeVSxv7OV34Ac), our team can take a closer look at it. We'll review the logs and configurations on our end to identify any potential issues.

3. **Logs and Error Messages**: If possible, could you provide any logs or error messages that appear during the export process? Even minimal information can be very helpful in diagnosing the problem.

4. **Alternative Approach**: As a temporary workaround, you might consider exporting the model to ONNX and then converting it to TensorFlow Lite using ONNX-TensorFlow converters. This isn't ideal but could serve as a stopgap solution.

We appreciate your understanding and cooperation. Our team is committed to resolving this issue for you. Please rest assured that we are looking into it and will get back to you with any findings or further steps.

**Comment by togro** [comment]
How can I check this ? :Verify Latest Versions: Ensure that you are using the latest version of the Ultralytics HUB and all relevant packages. Sometimes, updates include fixes for issues like these.Ultralytics HUB is a service from your company ....RegardsOn jul. 1 2024, at 10:23 pm, Paula Derrenger ***@***.***> wrote:Hello @togro,Thank you for providing additional details and for your patience. I understand the frustration when things don't work as expected, especially when other export formats are functioning correctly.Given that the issue seems specific to TensorFlow Lite and other formats like EdgeTPU and ONNX are working fine, it might be an isolated problem. Here are a few steps we can take to troubleshoot this further:Verify Latest Versions: Ensure that you are using the latest version of the Ultralytics HUB and all relevant packages. Sometimes, updates include fixes for issues like these.Model Review: Since you mentioned the model URL (https://hub.ultralytics.com/models/yGfk3twdeVSxv7OV34Ac), our team can take a closer look at it. We'll review the logs and configurations on our end to identify any potential issues.Logs and Error Messages: If possible, could you provide any logs or error messages that appear during the export process? Even minimal information can be very helpful in diagnosing the problem.Alternative Approach: As a temporary workaround, you might consider exporting the model to ONNX and then converting it to TensorFlow Lite using ONNX-TensorFlow converters. This isn't ideal but could serve as a stopgap solution.We appreciate your understanding and cooperation. Our team is committed to resolving this issue for you. Please rest assured that we are looking into it and will get back to you with any findings or further steps.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sergiuwaxmann** [comment]
@togro Hmm... This is strange - can you share your model ID with me so I can investigate this further? Also, do you have this issue with all your models?

**Comment by togro** [comment]
Model Id is : Potholes01-yolov8mI don't have problems with any other model, it's the only one I have problems with and the export to tensorflow lite.The only difference with the other models is that the size=1280, but I don't think that has anything to do with it.Anyway, as a workaround, I already installed a virtual one and used the yolo command line and the pytorch model to export it to tflite format.In any case, it is not the idea to go and put all that together to run a command instead of using the interface that you have so easy to use and well put together.Best RegardsOn jul. 2 2024, at 6:14 am, Sergiu Waxmann ***@***.***> ***@***.*** Hmm... This is strange - can you share your model ID with me so I can investigate this further? Also, do you have this issue with all your models?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sergiuwaxmann** [comment]
@togro I am glad you found a way to get the export working!
We will continue to improve Ultralytics HUB. Thank you for understanding!

**Comment by pderrenger** [comment]
Hello @togro,

Thank you for sharing the additional details and screenshots! It’s great to see the thoroughness of your testing.

It does seem like the issue might be related to the input size of 1280x1280. TensorFlow Lite can sometimes have constraints or limitations when handling larger input sizes, which might be causing the export to fail.

To further investigate, could you please ensure that you are using the latest version of the Ultralytics HUB and all relevant packages? Sometimes, updates include fixes for issues like these, and it's always good to rule out any version-related problems.

In the meantime, you might consider trying a slightly smaller input size, such as 960x960, to see if that resolves the issue. Here’s a quick example of how you might adjust the input size:

```python
# Example of adjusting input size
model = torch.hub.load('ultralytics/yolov5', 'yolov5m', pretrained=True)
model.conf = 0.25  # confidence threshold (0-1)
model.iou = 0.45  # NMS IoU threshold (0-1)
model.imgsz = 960  # set the input size to 960x960
```

If the issue persists, please let us know, and we will continue to look into it. Your feedback is invaluable, and we are committed to making the Ultralytics HUB as robust and user-friendly as possible.

Thank you for your understanding and patience. 😊

**Comment by togro** [comment]
Hello

I already solved this by setting up a virtual machine and generating the conversion in 1080.

I think that if your hub does not support those dimensions, it should not leave the option to generate conversion.

Or maybe the hub has some error, regarding what I was doing I already converted the model by hand.

Which is not the idea since you in the hub supposedly provide that functionality.

Greetings

**Comment by pderrenger** [comment]
Hello @togro,

Thank you for sharing your solution and feedback! 😊

I'm glad to hear that you managed to convert the model by setting up a virtual machine. Your point about the HUB potentially having limitations with certain dimensions is well taken. We strive to make the platform as user-friendly and robust as possible, and your insights are invaluable in helping us achieve that.

To ensure that this issue is addressed, could you please verify that you are using the latest version of the Ultralytics HUB and all relevant packages? Sometimes, updates include fixes for issues like these, and it's always good to rule out any version-related problems.

We appreciate your understanding that while the HUB aims to provide a seamless experience, there can occasionally be edge cases that require manual intervention. Your feedback helps us improve and refine the platform to better meet user needs.

If you encounter any further issues or have additional suggestions, please feel free to share them here. We're here to help and continuously improve the Ultralytics HUB experience for everyone.

Thank you again for your patience and cooperation!
