### ISSUE TITLE
Model won't train in Ultralytics Cloud, Disconnected Error

### ISSUE THREAD

**Issue by ahumphries2** [ultralytics/hub#829]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Signed up for the Ultralytics Cloud to train my models, it completely trains, starts optimizing weights and then gives me a Disconnected error.  Model https://hub.ultralytics.com/models/Bdcsog5ddsVZ4GQM0WR2

![image](https://github.com/user-attachments/assets/36d5bfff-d61f-42fc-be51-8f6cd8b741ae)

### Environment

Windows 10, MS Edge

**Comment by ahumphries2** [comment]
This issue is not resolved. Everytime I try to retrain the model it gets stuck and disconnected. Not sure how I'm disconnected when I'm using the Ultralytics Cloud, and I can't get access to the model until it completes the training and optimization. Please resolve or I need a complete refund of both the Ultralytics Hub Pro account and the Top Off charge.  Here is the model in Ultralytics:  https://hub.ultralytics.com/models/Bdcsog5ddsVZ4GQM0WR2
![image](https://github.com/user-attachments/assets/72a38546-0aff-443a-b641-755be75de197)

**Comment by sergiuwaxmann** [comment]
@ahumphries2 I forwarded your request and it should be processed soon.

Your issue reminds me of this issue: https://github.com/ultralytics/hub/issues/769. Maybe you have a similar problem (in the dataset)?

**Comment by ahumphries2** [comment]
I exported the dataset from Roboflow. Are you suggesting in #769 that I change the YAML file before I load into Ultralytics?

**Comment by ahumphries2** [comment]
I have Roboflow API linked to Ultralytics HUB.

I have a Roboflow Segmentation annotated dataset that I want to train as an OBB.  How do I do that in Ultralytics Hub?

Andy Humphries
Tech Manager – South Branch
O             (304) 530-1100 x1292
A             587 Robert C. Byrd Industrial Park Rd
              Moorefield, WV 26836

***@***.***

**Comment by glenn-jocher** [comment]
Hello Andy,

To train your Roboflow Segmentation dataset as an Oriented Bounding Box (OBB) in Ultralytics HUB, you'll need to ensure your dataset is correctly formatted for OBB tasks. Here's a general approach:

1. **Dataset Preparation**: Ensure your dataset annotations are compatible with OBB. This typically involves converting segmentation masks to OBB annotations. You might need to preprocess your dataset to achieve this.

2. **Integration**: Since you have the Roboflow API linked, ensure your dataset is imported correctly into Ultralytics HUB. Follow the integration guidelines to avoid any format issues.

3. **Training Setup**: Once your dataset is ready, you can proceed to set up your training in Ultralytics HUB. Select the appropriate model that supports OBB and configure your training parameters.

4. **Monitor and Adjust**: During training, monitor the results and adjust parameters as needed to optimize performance.

If you encounter any issues, please ensure you're using the latest version of Ultralytics HUB and feel free to reach out with specific questions. 😊

Best of luck with your training!

Ultralytics Team

**Comment by sergiuwaxmann** [comment]
@ahumphries2 Could the issue be dataset related or should we proceed with the refund?

**Comment by ahumphries2** [comment]
Please proceed with the refund, and change my account back to free from pro.  Thank you.

Andy Humphries
Tech Manager - South Branch

O             (304) 530-1100 x1292
A             587 Robert C. Byrd Industrial Park Rd
              Moorefield, WV 26836

***@***.***

**Comment by sergiuwaxmann** [comment]
@ahumphries2 Your request was processed. Apologies for the inconvenience.

**Comment by sergiuwaxmann** [comment]
@ahumphries2 Both refunds were issues. The refund process can take up to 10 working days.

**Comment by ahumphries2** [comment]
Thank you

Andy Humphries
Tech Manager – South Branch
O             (304) 530-1100 x1292
A             587 Robert C. Byrd Industrial Park Rd
              Moorefield, WV 26836

***@***.***

**Comment by sergiuwaxmann** [comment]
@ahumphries2 No worries!
