### ISSUE TITLE
Error while resume trainig on colab

### ISSUE THREAD

**Issue by Ibrahim-Ahrash** [ultralytics/hub#83]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

After colab got disconnected for some reason (my ISP I assume). I tried to resume training by copying the api and running the code. the training started from where it stopped epoch number 120. another disconnecting happened later and when tried to resume it 
I got the error message: UnboundLocalError: local variable 'epoch' referenced before assignment.

When colab disconnected the second time the epchos were on the last epoch 149 of 149

### Environment

google colab

**Comment by barney2074** [comment]
Colab is intended for interactive use, rather than long-running computations
It depends a bit on your subscription- Pro and Pro+ give you more resources and have longer runtime limits, but it also depends on what resources you have used recently.

I get that Google try to make it fair for everyone, but the downside is that it is unpredictable- if you are running something while there is low demand, it will probably stay running/connected for longer. Personally, I think a lot of Colab usage must be partial/disconnected jobs- so a lot of wasted resources

Although code can keep running if you close browser & reconnect- generally if you get forcibly disconnected, you've lost all data and need to start from the beginning


Andrew

**Comment by kalenmike** [comment]
@Ibrahim-Ahrash Thanks for letting us know. We will look into the resume functionality and see if we can find any bugs when resuming on the final epoch.
