### ISSUE TITLE
Timeout No response from servers

### ISSUE THREAD

**Issue by vanboven073** [ultralytics/hub#850]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi there!

I'm trying to upload a dataset (6.3 GB, 77974 Images). However when it states; optimizing, after a while it goes to the message: Timeout No response from servers.

Do you have a potential fix for this error?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @vanboven073, thank you for reporting an issue with the [ultralytics/hub](https://github.com/ultralytics/hub) repository! 🚀

Please take a look at our [HUB Docs](https://docs.ultralytics.com/hub) to explore more about our platform:

- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets): Get insights on how to prepare and successfully upload your datasets to HUB.
- [**Projects**](https://docs.ultralytics.com/hub/projects): Manage your models efficiently by grouping them into projects.
- [**Models**](https://docs.ultralytics.com/hub/models): Discover how to train and export your models.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations): Learn about various integration options for deploying models.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app): Run models on iOS and Android devices for enhanced mobile capabilities.
    - [**iOS**](https://docs.ultralytics.com/hub/app/ios): CoreML models on iOS for accelerated performance.
    - [**Android**](https://docs.ultralytics.com/hub/app/android): TFLite models on Android for optimized usage.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api): Use the API for cloud-based inference.

Since this may be a 🐛 bug, could you please provide us with a minimum reproducible example (MRE) and any relevant screenshots? This will help us better understand the issue and work towards finding a solution.

Thank you for your patience and understanding as an Ultralytics engineer will assist you soon! 😊

**Comment by pderrenger** [comment]
@vanboven073 hello!

Thank you for reaching out and providing details about the issue you're experiencing. It sounds like the dataset upload process is timing out due to its size. Here are a few steps you can try to resolve this:

1. **Check Your Internet Connection:** Ensure that your internet connection is stable and has sufficient bandwidth to handle large uploads.

2. **Try Uploading in Smaller Batches:** If possible, try splitting your dataset into smaller parts and upload them separately. This can help avoid timeouts due to large file sizes.

3. **Use the Latest Version:** Make sure you are using the latest version of the Ultralytics HUB. Updates often include performance improvements and bug fixes.

4. **Retry the Upload:** Sometimes, simply retrying the upload can resolve temporary network issues.

5. **Contact Support:** If the issue persists, consider reaching out to Ultralytics support through the [GitHub issues page](https://github.com/ultralytics/hub/issues) with details of your environment and any error logs.

We appreciate your patience and understanding. If you have any further questions or need additional assistance, feel free to ask. 😊

**Comment by yogendrasinghx** [comment]
Hi @vanboven073, thanks for reaching out!

We currently have no issues on our end with uploading valid datasets to Ultralytics HUB. To ensure your dataset is formatted correctly, please watch this [YouTube video: Upload Datasets to Ultralytics HUB ](https://www.youtube.com/watch?v=R42s2zFtNIY), which provides a step-by-step guide for creating a valid dataset for Ultralytics HUB. Once you've checked your dataset, try uploading it again following the instructions in the video and in the [documentation here](https://docs.ultralytics.com/hub/datasets/#upload-dataset).

If the issue persists, please let us know with any additional details, such as a screenshot or a sample of your dataset structure. This will help us assist you further. Thank you for your patience!
