### ISSUE TITLE
Your account is being deleted.

### ISSUE THREAD

**Issue by crimate** [ultralytics/hub#857]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

I accidentally pressed "Delete Account" button in place of sign out and that is causing me this problem. Is there any way to solve this problem ? My emails is: sazzad.crimate@gmail.com

Thanks in advance.

### Environment

Computer: Asus TUF F15
OS: Windows 11
Browser: Chrome Latest Update

### Minimal Reproducible Example

1. Problem while logging in.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @crimate, thank you for reporting this issue regarding the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀! We understand the importance of your account, and we're here to help.

Please check out our [HUB Docs](https://docs.ultralytics.com/hub) for more information:

- [**Account Management**](https://docs.ultralytics.com/hub/account). Learn more about managing your account settings and options.
- [**Help and Support**](https://docs.ultralytics.com/help). Access resources for troubleshooting and support.

Since this seems to be a 🐛 Bug Report or urgent issue, could you provide any additional details or screenshots that might help in understanding the problem further? Here's a guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that might be helpful.

Thank you for your patience. An Ultralytics engineer will review your issue and get back to you soon! 😊

**Comment by sergiuwaxmann** [comment]
@crimate Hello! Your account has been successfully restored!
