### ISSUE TITLE
Training Disconnected

### ISSUE THREAD

**Issue by joseabraham** [ultralytics/hub#940]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

My model training got disconnected at Epoch 34, tried Resume Training a few times but without any luck.
Pleas help I've been billed already for 31 hours.

Link to model
https://hub.ultralytics.com/models/GLFniB2dXZSYyas5azQU?tab=train

**Comment by UltralyticsAssistant** [comment]
👋 Hello @joseabraham, thank you for bringing this issue to our attention regarding [Ultralytics HUB](https://hub.ultralytics.com) 🚀! Please take a moment to review our [HUB Docs](https://docs.ultralytics.com/hub) for more detailed information:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Start training and deploying YOLO models with HUB in seconds.
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets). Learn how to prepare and upload your datasets to HUB in YOLO format.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Group your models into projects for improved organization.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Train YOLOv5 and YOLOv8 models on your custom datasets and export them to various formats for deployment.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations). Explore different integration options for your trained models, such as TensorFlow, ONNX, OpenVINO, CoreML, and PaddlePaddle.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app). Learn about the Ultralytics App for iOS and Android, which allows you to run models directly on your mobile device.
    * [**iOS**](https://docs.ultralytics.com/hub/app/ios). Learn about YOLO CoreML models accelerated on Apple's Neural Engine on iPhones and iPads.
    * [**Android**](https://docs.ultralytics.com/hub/app/android). Explore TFLite acceleration on mobile devices.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api). Understand how to use the Inference API for running your trained models in the cloud to generate predictions.

If this is a 🐛 Bug Report, could you please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) with additional information such as:
1. Detailed steps to reproduce the issue.
2. Any relevant screenshots, logs, or error messages.
3. Your HUB environment details (e.g., browser or operating system) if applicable.

This will help us investigate and address the issue more efficiently. Additionally, if your model training was interrupted during training at Epoch 34, ensure that you are following these [resume training guidelines](https://docs.ultralytics.com/hub/models/#resuming-training).

Our team has noted your report, and an Ultralytics engineer will assist you shortly. Thank you for your patience! 😊

**Comment by pderrenger** [comment]
@joseabraham hi, thank you for reaching out and sorry to hear about the training issue! Let’s get this resolved for you.

The Ultralytics HUB offers a **Resume Training** feature, allowing you to continue model training from the last saved checkpoint. Since the "Resume Training" attempts haven’t been successful, here are some steps to follow:

1. **Verify Environment and Connection**  
   Ensure your internet connection is stable as disruptions during training may cause issues. Additionally, check if the HUB servers are operational.

2. **Retry Resume Training**  
   - Go to your model’s **Training tab** in the link you've provided.
   - Click the **Resume Training** button and ensure resources (like account balance) are sufficient.

3. **Logs for Diagnostics**  
   - Check the **Logs Section** of the training panel for any errors during the disconnection. These logs will give more insight into what caused the disconnect.

4. **Account Balance**  
   For training sessions billed per epoch, make sure your account balance is sufficient for the resumed processes. Cloud sessions may pause or halt if the balance falls below the required threshold.

5. **Contact Support for Billing Adjustments**  
   While the HUB ensures billing fairness, if your session was cut short due to technical issues, you can reach Ultralytics via [HUB Support](https://hub.ultralytics.com/support) to address billing concerns.

For continued troubleshooting, feel free to attach any additional logs. Also, remember you can always monitor training progress through the **Ultralytics HUB** interface for live insights. If the issue persists, providing more details (like error messages or screenshots) will help us assist further.

Thank you for your patience! 😊

**Comment by sergiuwaxmann** [comment]
@joseabraham Maybe something went wrong (e.g., bad internet) during the upload of the `best.pt`...
Your last training uploaded a checkpoint for `epoch-98.pt` so I updated your model to use `epoch-98.pt` instead of `epoch-34.pt`. Can you try resuming training again? Let me know if everything works well this time.

**Comment by yogendrasinghx** [comment]
@joseabraham Already replied on [1122](https://github.com/ultralytics/hub/issues/1122) issue.
